### ISSUE TITLE
Hotkeys don't work after alt+tab

### ISSUE THREAD

**Issue by Lexx2k** [alexbatalov/fallout2-ce#1]
Started the game in window mode, after alt+tab out of it and then going back, none of the hotkeys are working anymore.

**Comment by alexbatalov** [comment]
The way keyboard processing is done in F2 does not fit very well into SDL and require major overhaul. It will take some time.

**Comment by Lexx2k** [comment]
There seems to be another alt+tab issue -- when not using windowed mode, my game froze after returning to it with alt+tab.

**Comment by alexbatalov** [comment]
Probably fixed, please check.

**Comment by Lexx2k** [comment]
Hotkeys are working now in window mode. Outside of window mode the game is still frozen after alt-tab.

**Comment by alexbatalov** [comment]
Sfall has the same behaviour, no? When I alt-tab to other window, the game and music stops.

**Comment by Lexx2k** [comment]
Sure, but when returning to the game it works again. Here everything remains frozen.
