### ISSUE TITLE
Debug Android .apk creates read-only folders

### ISSUE THREAD

**Issue by c6-dev** [alexbatalov/fallout2-ce#105]
I was following installation instructions for Android from the readme, but it seems that the junk folders that the .apk created in `com.alexbatalov.fallout2ce.debug/files` are read-only, i can't delete them on PC or the device itself (it's not rooted). Trying to overwrite them with Fallout 2 data files also fails.  

<img src=https://user-images.githubusercontent.com/31777460/181898577-56459c16-e65c-4f54-90b3-aa8c4bd5556e.png width="400">

**Comment by c6-dev** [comment]
After googling for a bit, it seems Google changed some permissions regarding /android/data in 11+, so this probably isn't the .apk's fault. Still not sure how to go about this, though.

**Comment by APAmk2** [comment]
That's is half-offtopic comment, but i want ask, how you compiled apk? I don't know how cmake works, but i want to test FO2-ce on my phone, i would be grateful for an answer.

**Comment by c6-dev** [comment]
You don't need to compile anything, select Actions tab, click on the latest workflow run and scroll down to artifacts.

**Comment by APAmk2** [comment]
Thanks a lot!

**Comment by strikersix23** [comment]
devilution fixed this issue by using an import dialog by holding the icon on android launcher to import data. Dolphin emu used an import /export dialog in the setting. Opentouch used android SAF to select the folder to read/write data from. 

https://developer.android.com/guide/topics/providers/document-provider
https://developer.android.com/guide/topics/providers/create-document-provider

https://developer.android.com/training/data-storage/use-cases
https://developer.android.com/training/data-storage/manage-all-files
https://developer.android.com/training/data-storage/shared
https://developer.android.com/guide/topics/data

source use

https://github.com/emileb/SAFFAL

SAF lib

**Comment by c6-dev** [comment]
Just tried, works perfectly now, thanks a bunch. The only thing is i had to delete the folder in android/data that was left over from the previous build for it to start up.
