### ISSUE TITLE
Global refactoring

### ISSUE THREAD

**Issue by JordanCpp** [alexbatalov/fallout2-ce#11]
Greetings!

The code is confusing. I want to turn functions into static classes. This will break dependencies. Remove global variables. Remove extern variables. The changes will affect all code. Are you ready to accept commits?

After refactoring. Pass dependency to constructor. Opens the door to writing tests.

**Comment by JordanCpp** [comment]
After refactoring. Pass dependency to constructor.

**Comment by alexbatalov** [comment]
I'm not sure I got you. Define "confusing". Remeber this code was written almost 25 years ago in a hurry. Add decompilation mess. But I don't see how static classes would help to alleviate it. What it would do is create even more mess and make Reference Edition virtually incompatible with Community Edition, which means more time to manage two projects. Keep in mind that some important window functions is still missing, which are used by many mods (some require sfall additions, but still use built-in window system). I definitely see your point in making things more test-friendly. We'll do it in time. You can help with migrating Sfall features to CE. Once it's ready we'll devise a plan on modernizing the code.

**Comment by JordanCpp** [comment]
> Once it's ready we'll devise a plan on modernizing the code.


I agree.
