### ISSUE TITLE
First aid skill of Allies

### ISSUE THREAD

**Issue by CD4NV** [alexbatalov/fallout2-ce#110]
When one of the teammates is near death, he tries to use the first aid skill.
Most likely, this is a mistake, since teammates are trying to apply treatment using the player's skill.
Save File: [SLOT08.zip](https://github.com/alexbatalov/fallout2-ce/files/9237909/SLOT08.zip)
After downloading the file, you will notice that Sulik is near death and the console constantly displays messages that you have exhausted your skills.

**Comment by alexbatalov** [comment]
This one was hard to find. There was indeed a bug in managing skills usage time slots. The messages themselves (that you have exhausted your skills when you really are) are expected and can be seen in vanilla under same circumstances.
