### ISSUE TITLE
When selling slaves to Metzger, the player does not receive money.

### ISSUE THREAD

**Issue by CD4NV** [alexbatalov/fallout2-ce#111]
Save File: [SLOT05.zip](https://github.com/alexbatalov/fallout2-ce/files/9238083/SLOT05.zip)
Having sold a teammate to Metzger (for example, Sulik), the player does not receive money.

**Comment by WastelandBoy** [comment]
I haved the same issue but for me it work just fine and have no issues at all after 1.0.1 on PS VITA!

I use the vanilla files (original 1998 files, no steam/gog) clean, no sfall extensions.

And let me say this, it feels so nice play fallout on this little device!

PS.
Sorry for my bad English, I'm from Italy.

**Comment by CD4NV** [comment]
> I cannot reproduce it. There is no message in the in-game monitor, but player receives money as expected. Exactly the same behaviour is seen in vanilla. Please check on other platforms to make sure it is Vita-only issue.

OK, I'll try win version. And the amount of money can be checked in the inventory before and after the sale, so as not to pay attention to the console.

**Comment by CD4NV** [comment]
I checked this save file on Vanilla version — Metzger gives money for the sale of slaves.
Downloaded the latest release (development build) today and ... Oh, a miracle — Metzger gives money for slaves sold. If edits have been made to the latest release, then this issue can be marked as completed. Thanks.
