### ISSUE TITLE
Hijacked Highwayman and Silent T-Ray

### ISSUE THREAD

**Issue by CD4NV** [alexbatalov/fallout2-ce#113]
Name of the quest: «Recover your stolen car».
Port Version: PS Vita Development Build (Latest Release).
Save File: [SLOT06.zip](https://github.com/alexbatalov/fallout2-ce/files/9270793/SLOT06.zip)

This quest can be completed in 3 ways:
1. Follow the tracks (You need to go to the parking lot and select from the drop-down menu: Follow the tracks).
2. Talk to Cody, after which Cody will take the player to the stolen car (Cody can be found near Cat's Paw brothel).
3. Talk to Jules (he is located next to the parking lot). After the threat, Jules will take the player to the car.

The first bug: If you talk to Cody, then according to the rules of the quest, the player gets 500 exp. The same condition must be met when talking to Jules. But when talking to Jules, the player does not gain experience. According to the rules of this quest, the player must receive 500 exp in both cases, except if the player chose the first way: Follow the tracks - in this case, experience points aren't provided.
And the second bug that makes this quest impassable: Once in the workshop with a stolen car, the player must talk to T-Ray (he is in a room at the top of the map). But T-Ray absolutely does not react to the player in any way, he simply does not enter into a dialogue.

**Comment by alexbatalov** [comment]
Jules behaviour is the same in vanilla (no exp). [Fandom](https://fallout.fandom.com/wiki/Recover_your_stolen_car) also does not mention experience from Jules. T-Ray is fixed (there is a bug in scripting, which vanilla/RE silently ignores, and CE was crashing due to stricter type management).

**Comment by CD4NV** [comment]
> Jules behaviour is the same in vanilla (no exp). [Fandom](https://fallout.fandom.com/wiki/Recover_your_stolen_car) also does not mention experience from Jules. T-Ray is fixed (there is a bug in scripting, which vanilla/RE silently ignores, and CE was crashing due to stricter type management).

Thanks a Lot. I was guided by the Russian version of [Fandom](https://fallout.fandom.com/ru/wiki/Найти_свой_угнанный_автомобиль ). Apparently they made a mistake when translating.
