### ISSUE TITLE
Screensaver in PipBoy

### ISSUE THREAD

**Issue by CD4NV** [alexbatalov/fallout2-ce#115]
Port Version: PS Vita Development Build (Latest Release).
If the player opens a pip fight and does not do anything in it, then after a while the screensaver in the form of falling atomic bombs will begin.
In the port, after waiting, the screen on the right simply goes out, while there are no falling atomic bombs.
P.S.: This is certainly not quite a bug, but would like this port to be as authentic as possible to the original of the game.
P.P.S.: In the win version, the screensaver works.

**Comment by Northfear** [comment]
You should probably create port specific issues on the page of the port itself to keep things cleaner here.

**Comment by CD4NV** [comment]
> You should probably create port specific issues on the page of the port itself to keep things cleaner here.

Ok. Is it on your page? I'm just already confused about these ramifications. Releases are released in one place, the description is on another, the issue was only opened here until recently.

**Comment by Northfear** [comment]
I've just totally forgot about making issues section available in my fork and it was closed up until recently.
The general rule is that issues should be created here if they're also reproducible on PC version.
Otherwise they should go here
https://github.com/Northfear/fallout2-ce-vita/issues
Since they're only reproducible on PSV.

**Comment by CD4NV** [comment]
> I've just totally forgot about making issues section available in my fork and it was closed up until recently. The general rule is that issues should be created here if they're also reproducible on PC version. Otherwise they should go here https://github.com/Northfear/fallout2-ce-vita/issues Since they're only reproducible on PSV.

OK, thanks for the clarification.

**Comment by Northfear** [comment]
@alexbatalov ok, this one is weird. It works well on Windows indeed, but the PipBoy screen is just empty on Linux.
So looks like it's not PSV only problem after all.
