### ISSUE TITLE
Dedicated touch buttons for in games menus Android version

### ISSUE THREAD

**Issue by TrellBell** [alexbatalov/fallout2-ce#117]
Would dedicated touch buttons for in game menus be possible? It would help on android.  
  
Also I saw in a previous post the black bars on the side were a resolution issue. How do I adjust that for a 20:9 device? I didn't see an ini file in my android file browser with my data files. Do I need to do that on pc first then transfer the files?

**Comment by alexbatalov** [comment]
Touch controls is a subject to change, that's for sure, but it's not a priority right now. For resolution you need to upload `f2_res.ini` along with the game data files. Open with any text editor, look for `SCR_WIDTH` and `SCR_HEIGHT`. For 20:9 device it's 1067x480.

**Comment by TrellBell** [comment]
Sounds good. Thank you for clearing that up for me and for making this app happen.
