### ISSUE TITLE
Font size on Android phones

### ISSUE THREAD

**Issue by WastelandBoy** [alexbatalov/fallout2-ce#119]
I wonder if there's a way to increase the large of the font on Android.

I have an Android Phone Motorola 5 inches and a Nokia x100 (6 inches) In Both cases is hard to play for more than 1 hour because of the Font size.

**Comment by alexbatalov** [comment]
Not at this time, sorry. There are no suitable fonts. These are bitmap fonts, hence there is no way to make it "slightly larger", the only way is to redraw every symbol. Up next, there are many hardcoded positions and sizes, which were designed with default font in mind. Increasing font size will likely break a lot of things in an unpredictable way. Dialog window (where you interact with text a lot) was designed without scrolling support, so you won't be able to see all your options if font size is increased. All of these will be addressed at some point, but it's not a priority right now.

**Comment by WastelandBoy** [comment]
I understand, thanks for the answer and keep the good work!
