### ISSUE TITLE
Android app crashes while starting the game

### ISSUE THREAD

**Issue by edgarmiro** [alexbatalov/fallout2-ce#122]
In my Android 11 tablet, I select the Fallout 2 folder and then, it loads the data and starts the game but it crashes.
I've tried in two ways:
- Copying the whole F2 folder: It crashes in the first loading screen of the game.
- Copying just the necessary files (Explained in the readme file): It crashes in the PLEASE STAND BY screen.

Thanks in advance!

**Comment by alexbatalov** [comment]
Looks like a language pack issue. Make sure your game data files matches the language set in `fallout2.cfg`. Follow instructions for desktop, if you're on Windows, just drop-in `fallout2-ce.exe` into game directory. Make sure it works. If it does, copy this directory to your tablet. Reinstall `apk` and pick this folder.

**Comment by edgarmiro** [comment]
I did it but sadly, the results are the same. Opening the exe files on Windows run perfectly.

**Comment by alexbatalov** [comment]
1. What is your Android 11 device exactly? I'm not sure it will help, but I'll see if there are any known issues.
2. What do you mean not fullscreen on Android 12? Post screenshot if possible.

**Comment by edgarmiro** [comment]
> 1. What is your Android 11 device exactly? I'm not sure it will help, but I'll see if there are any known issues.
> 2. What do you mean not fullscreen on Android 12? Post screenshot if possible.

1. The device is: Samsung Galaxy Tab A (SM-T510)
2. ![Screenshot_20220807-232845.png](https://user-images.githubusercontent.com/2278900/183311606-e74e74dd-5c4d-4818-9651-a38bb9ae7c97.png)

**Comment by edgarmiro** [comment]
Sorry! I've just discovered it's possible to change the resolution in f2_res.ini file!
![Screenshot_20220808-090808.png](https://user-images.githubusercontent.com/2278900/183359950-14c2ea16-d1c8-44d9-a5e6-ccc3d8439e35.png)
My fault 🙃
So, the problem is in the Android 11 tablet, which still crashing.
Thanks!!

**Comment by alexbatalov** [comment]
Everything is super tiny, it should not be like that. Set screen height to 480 and calculate width depending on your screen ratio. Assuming screenshot size is authentic (2400x1080), that's 20:9 device, set width to 1067.

**Comment by c6-dev** [comment]
I found that 1200x540 also works very well for 20:9.

**Comment by APAmk2** [comment]
I have same problem on my xiaomi redmi 9a, Android 10, i can run and play game on windows, bur it crashes on Android.

**Comment by edgarmiro** [comment]
> Everything is super tiny, it should not be like that. Set screen height to 480 and calculate width depending on your screen ratio. Assuming screenshot size is authentic (2400x1080), that's 20:9 device, set width to 1067.

Thanks! Much better now in my phone!

![Screenshot_20220808-111327.png](https://user-images.githubusercontent.com/2278900/183410525-73e04597-7a56-4be2-aeff-053b18dc2d78.png)

**Comment by edgarmiro** [comment]
[log.txt](https://github.com/alexbatalov/fallout2-ce/files/9281448/log.txt)
@alexbatalov Just in case it helps, I've attached the log while crashing in the Android 10 tablet. 🙂

**Comment by APAmk2** [comment]
[log.txt](https://github.com/alexbatalov/fallout2-ce/files/9281468/log.txt)

**Comment by APAmk2** [comment]
I tested debug apk just now and it works perfectly.

**Comment by alexbatalov** [comment]
Can you please check which of these works (assuming the same game data folder is selected):
- v1.0.3 debug: https://github.com/alexbatalov/fallout2-ce/actions/runs/2781487838
- v1.0.3 release: https://github.com/alexbatalov/fallout2-ce/releases/tag/v1.0.3
- latest debug: https://github.com/alexbatalov/fallout2-ce/actions/runs/2816707738

To justify things try to use GOG files:
- `data`
- `sound`
- `master.dat`
- `critter.dat`
- `patch000.dat`

Do not upload `fallout2.cfg` or `f2_res.ini` for testing.

**Comment by APAmk2** [comment]
1.0.3 release not works, latest and 1.0.3 debug works fine.

**Comment by edgarmiro** [comment]
In my case, I launched the debug version from Android Studio.

**Comment by bouncingbenji** [comment]
Where can I find the f2_res.ini file? Pleazw and how would I go about changing the size have you got a picture so I put it in the right spot? I'm running a Samsung galaxy s21

**Comment by edgarmiro** [comment]
That file comes at the same required files level. You just have to edit it and select the resolution.

**Comment by S1aVa2021** [comment]
I have same problem on my Samsung galaxy A01 Core, Android 10. Game crashes on "Please stand by"

**Comment by alexbatalov** [comment]
@S1aVa2021 Which data files are you using (original CD, GOG, Steam)?

**Comment by S1aVa2021** [comment]
> 

CD with Russian translate and English GOG version
Both of them doesn't work

**Comment by alexbatalov** [comment]
- Remove apk from your phone
- Install release version: https://github.com/alexbatalov/fallout2-ce/releases/tag/v1.0.3
- Install debug version: https://github.com/alexbatalov/fallout2-ce/actions/runs/2888827981
- On your PC create a new folder - `fallout2-min`, copy only these files from GOG version:
```
master.dat
critter.dat
```
- Copy this folder to your phone
- Try running in release version.
- Try running in debug version.
- Post your results.

**Comment by S1aVa2021** [comment]
Thank you, debug version works

**Comment by alexbatalov** [comment]
What about release?

**Comment by 4lejandr000** [comment]
> * Remove apk from your phone
> 
>     * Install release version: https://github.com/alexbatalov/fallout2-ce/releases/tag/v1.0.3
> 
>     * Install debug version: https://github.com/alexbatalov/fallout2-ce/actions/runs/2888827981
> 
>     * On your PC create a new folder - `fallout2-min`, copy only these files from GOG version:
> 
> 
> ```
> master.dat
> critter.dat
> ```
> 
>     * Copy this folder to your phone
> 
>     * Try running in release version.
> 
>     * Try running in debug version.
> 
>     * Post your results.

hi, i have the same problem in Samsung Galaxy A10e android 11, the "copiying files" process is ok, but just stop on "starting game". How i can download, the debug version? 

sorry for my bad english

**Comment by alexbatalov** [comment]
Go to "Actions" tab, open latest workflow run and scroll down to "Artifacts" section.

**Comment by 4lejandr000** [comment]
> Go to "Actions" tab, open latest workflow run and scroll down to "Artifacts" section.

fallout-ce-debug.apk works fine, the game start, and mouse and keyboard works :D

![Screenshot_20221228-141949_Fallout 2 (Debug).jpg](https://user-images.githubusercontent.com/86433387/209855794-5f8b4735-abeb-4559-b6eb-07ec36de24d6.jpg)

thanks you, very much. 

I can send you, some info or log file, to help you in this issue?

**Comment by alexbatalov** [comment]
You're welcome. The logs are useless for this case, but you can test a couple of builds if you want to help. I think I've found the source of this issue (memory alignment), I can prepare special builds with workarounds just to confirm I'm on the right track.

**Comment by 4lejandr000** [comment]
yes, i can test the builds. How i can get the installers?

**Comment by 4lejandr000** [comment]
yes, i can test the builds. How i can get the installers?

**Comment by alexbatalov** [comment]
@APAmk2 @4lejandr000 Hey guys, can you please check if this release does not crash. It's a v1.1.0 with cherry-picked memory alignment fixes. There are some undefined behaviour stuff when playing movies, but I believe fixing art (2714dc1ea14b3786e28be3a631bae0dd43fe3b8f) will actually do the trick.

[app-release.apk.zip](https://github.com/alexbatalov/fallout2-ce/files/10459845/app-release.apk.zip)

**Comment by APAmk2** [comment]
Yeah, works fine and game doesn't crashing

**Comment by alexbatalov** [comment]
Terrific, I guess it's time to prepare a new release.
