### ISSUE TITLE
Hi-resolution pack would it work??  

### ISSUE THREAD

**Issue by bouncingbenji** [alexbatalov/fallout2-ce#124]

**Comment by tytannial** [comment]
> _No description provided._

yes, just put the f2_res.ini to your game folder and set the resolution with SCR_WIDTH and SCR_HEIGHT.

**Comment by bouncingbenji** [comment]
Thank but do u know how I would find out the resolution for a galaxy s21??

**Comment by alexbatalov** [comment]
Use 480 as a height, S21 has 20:9 screen ratio, so your width should be 1067.

**Comment by bouncingbenji** [comment]
Thank you very much I shall give that a try tonight! It's a great piece of work so far...
