### ISSUE TITLE
Screen too Small

### ISSUE THREAD

**Issue by Astrolunatic06** [alexbatalov/fallout2-ce#126]
I'm using a Samsung Galaxy A32 5G.
How do I make the game fullscreen or bigger?
I tried changing the res in f2_res.ini

**Comment by alexbatalov** [comment]
Post screenshot and your settings `SCR_WIDTH`, `SCR_HEIGHT` from `f2_res.ini`

**Comment by bouncingbenji** [comment]
![Screenshot_20220809-195116_Fallout 2.jpg](https://user-images.githubusercontent.com/61379821/183738534-4ee204a9-e6d3-4085-ba59-574ae8b248f6.jpg)

Something like this be OK??

**Comment by bouncingbenji** [comment]
![Screenshot_20220809-195257_Fallout 2.jpg](https://user-images.githubusercontent.com/61379821/183738669-dc7963b1-9538-480c-b233-5833bea9bb99.jpg)

**Comment by alexbatalov** [comment]
Main menu is fine, it uses original size on all resolutions (640x480). Provide `f2_res.ini` along with the game data files:

```ini
[MAIN]
SCR_WIDTH=1067
SCR_HEIGHT=480
```

**Comment by bouncingbenji** [comment]
Seems to slow the game play down a touch but not very noticeable thank you...

**Comment by bouncingbenji** [comment]
Also it only makes the game screen bigger the pipboy bit at the bottom that stays the same..

**Comment by bouncingbenji** [comment]
![Screenshot_20220810-134201_Fallout 2.jpg](https://user-images.githubusercontent.com/61379821/183904021-729a5bba-94e8-4f29-87c2-f9085ac54534.jpg)

Worked fine just the bit at the bottom did not change

**Comment by alexbatalov** [comment]
Add this to the `f2_res.ini`:

```ini
[IFACE]
IFACE_BAR_MODE=1
```

**Comment by bouncingbenji** [comment]
Just type this anywhere? Thank you..

Plus do u have a donation tab?

**Comment by bouncingbenji** [comment]
Thank you..

Plus do u have a donation tab? As I think I'd like to send some to your work!! ![Screenshot_20220810-150732_Fallout 2.jpg](https://user-images.githubusercontent.com/61379821/183922279-5d85f9d0-9bc9-4f74-b141-9998a5e75f35.jpg)

**Comment by alexbatalov** [comment]
@Astrolunatic06 Did you solve your problem? Can we close this?

@bouncingbenji You're welcome. I don't think I'm in position to accept donations for anything related to Fallout 2. Spreading the word is the best thing you can do.

**Comment by bouncingbenji** [comment]
Yes it's resolved but the money is for the work your putting in to the apk mate that's all
