### ISSUE TITLE
Gamepad controls mapping

### ISSUE THREAD

**Issue by goooroooX** [alexbatalov/fallout2-ce#132]
This is a feature request, to support gamepads. This will be super handy for Android portable handhelds. Any kind of gamepad support is highly appreciated (fixed control scheme as easiest option).

**Comment by bouncingbenji** [comment]
That would be so cool!! Playing with a external controller

**Comment by alexbatalov** [comment]
It's on the roadmap.

**Comment by goooroooX** [comment]
Great!
