### ISSUE TITLE
San Fransisco

### ISSUE THREAD

**Issue by inetpubACE** [alexbatalov/fallout2-ce#133]
Ring in San Fransisco doesnt work - it wont transfer you to ring when youll challenge Dragon or Lo

**Comment by alexbatalov** [comment]
Post your savegame

**Comment by inetpubACE** [comment]
[SLOT07.zip](https://github.com/alexbatalov/fallout2-ce/files/9353392/SLOT07.zip)

**Comment by inetpubACE** [comment]
did speedrun and 100% gameplay, found this bug only! GOOD JOB

**Comment by inetpubACE** [comment]
uh and sometimes youre getting black bottom till youll open stats and its really hard to swipe world map - mouse doesnt stick to look around map (playing fhd res)

**Comment by alexbatalov** [comment]
1. Do you have a save game in San Francisco? The one you attached is a final fight with Frank Horrigan.
2. Please elaborate on this black bottom thing. Is it flickering interface bar when loading game/map?
3. World map scrolling fixes are on the roadmap. If you're using debug version you can use mouse wheel for scrolling.
