### ISSUE TITLE
Android controls 

### ISSUE THREAD

**Issue by lelouchsama9** [alexbatalov/fallout2-ce#136]
Greetings ,
Check the fo2.exe on play store for Android it can run fallout 1 and 2 but got issues right now with some controls and it can only run original fallout it got controls with touchscreen gestures it might be a nice example , you could also swap controls to be one click instead of 2 clicks and 2 clicks instead of 3 ! 
Also adding custom buttons is an easy way to get hold of everything fast enough .
No need to drag the mouse pointer all across the screen it's .
I love the project, good luck for you all.

**Comment by bouncingbenji** [comment]
Now going to check this one out

**Comment by lelouchsama9** [comment]
> Now going to check this one out, also how did u get fo2.exe to work? I keep getting executable not found?

Check the name of you exe ?! 
I got the gog version which is the same as all the other versions it runs version 1.2 and it got the same issue with drag and hold controls not working ! 
Tell me if it worked with you 
Your best option is the original fallout game .
