### ISSUE TITLE
Stuck at Fade Black and certain dialogue interface

### ISSUE THREAD

**Issue by melvyoutube** [alexbatalov/fallout2-ce#138]
Running on MacOS with Steam Fallout 2, I noticed there are some issues with Fade Black and dialogue interface at certain scenes.

At Modoc, if you sleep Grisham's children, the screen will fade black and stuck at black screen
At Vault City, if you encounter Vic's daugther for the first time with Vic in party, the screen will fade black stuck at black screen
At the Den, during the quest to deliver meal for Mom, dialogue with Smitty result in a stuck dialogue interface where the character can still be moved around. The meal is never removed from inventory but the quest is considered completed

**Comment by alexbatalov** [comment]
Please post your savegames so I can check your problems.

**Comment by melvyoutube** [comment]
[SLOT02.zip](https://github.com/alexbatalov/fallout2-ce/files/9389310/SLOT02.zip)
Please find this save slot - right before the dialogue with Valerie (Vic's Daughter)

**Comment by alexbatalov** [comment]
This one is fixed in dcb53393c12be6e1f8cd9ae91d01ccd0c115817a. Please wait for the next release cycle (early September).
