### ISSUE TITLE
Would this work on the ppsspp emulator?? 

### ISSUE THREAD

**Issue by bouncingbenji** [alexbatalov/fallout2-ce#139]

**Comment by lelouchsama9** [comment]
I very hope so my man ! 
Would be a great port for Android

**Comment by LXRD-LXNELINESS** [comment]
> 



> I very hope so my man ! Would be a great port for Android

Isn't it already ported for android? There is an apk for v1.0.3, you just need the game files.

**Comment by lelouchsama9** [comment]
> > 
> 
> > I very hope so my man ! Would be a great port for Android
> 
> Isn't it already ported for android? There is an apk for v1.0.3, you just need the game files.

It's already a great port and a very optimized one , but it's a bit far from perfect !
Controls scheme right now ain't the best . 
It's the only major problem I faced

**Comment by TrellBell** [comment]
Youre thinking of the vita version, which would not work on ppsspp.

**Comment by WastelandBoy** [comment]
The PS VITA Port is amazing!.
The controllers are just perfect, Northfear did a great job , you can use both touch or phisical buttons. .. 

Thanks to Northfear and the whole team behind Fallout 2 CE,.
