### ISSUE TITLE
Configurable starting map

### ISSUE THREAD

**Issue by JanSimek** [alexbatalov/fallout2-ce#14]
Feature proposal to make the starting map configurable. My use case is to launch fallout directly from [my map editor](https://github.com/JanSimek/geck-map-editor). Modders will find this useful for testing their maps without having to recompile fallout2-ce.

Sfall already includes this option:

```ini
[Misc]
;To start a new game somewhere other than artemple.map, uncomment the next line and set it to the map you want to load
;StartingMap=
```

**Comment by Lexx2k** [comment]
I thought all Sfall features will be taken over anyways. :>

**Comment by JanSimek** [comment]
You are right. I misread the README.
