### ISSUE TITLE
Multiple black screen issues 

### ISSUE THREAD

**Issue by lelouchsama9** [alexbatalov/fallout2-ce#140]
Some dialogue in vault city , NCR ( zeta scan ) causes black screen .

**Comment by alexbatalov** [comment]
Please post savegame.

**Comment by lelouchsama9** [comment]
> Please post savegame.

To be completely honest with you I deleted the whole thing cuz I got angry of these black screens and it ruined my playthrough ! 
Zeta scan gives two points into luck ( no way I'm giving that up even it costs the whole playthrough )

**Comment by alexbatalov** [comment]
Assuming you used release version (v1.0.3) there was a bug (#128) which has already been fixed. Wait till the next release cycle (early September) or you use a debug version.
