### ISSUE TITLE
macOS version black screen in Maintenance center

### ISSUE THREAD

**Issue by mxshooter** [alexbatalov/fallout2-ce#142]
Hello!
Thank you for the opportunity to play the classics on macOS!
In the process of passing, I reached a reproducible bug:
In Vault City (Maintenance Center) when trying to talk to Valerie after her "Oh.. Oh...Dad?" and the answer from my side the screen goes black and nothing happens. I'm using GOG game version 2.1.0.18 on Monterey 12.5.1.
Save - https://www.dropbox.com/s/8fj2wqns98fr9cr/SLOT06.zip?dl=1

**Comment by alexbatalov** [comment]
Hey, this bug was fixed in dcb53393c12be6e1f8cd9ae91d01ccd0c115817a. Please wait for next release cycle (early September) or use latest development build (note that it's not signed/notarized).
