### ISSUE TITLE
[Android] Mutiple bugs on in-game graphic cutscene events

### ISSUE THREAD

**Issue by Rottengut** [alexbatalov/fallout2-ce#149]
II'm using Samsung Galaxy Tab S6 and GOG version of Fallout 2.

Throughout the game, the events which show short cutscenes with in-game graphic(cutscenes without FMVs).

For example, arm wrestling quest or competition with intelligent Radscorpion in Broken Hills and Hubologist baptism thingy or Officer Jack trying to blow up the reactor scene in NCR didn't work.

After I selected the option which shows the Chosen One doing things with NPCs, nothing happened. They were just standing and doing nothing. Also, I couldn't talk with the NPC(Francis, Professor, Enlightened One, Officer Jack) after that. I was able to pickpocket or attack them, but choosing the conversation option didn't show up anything.

However, some cutscenes like Frank Horrigan killing the poor family worked normally.

English isn't my first language, so forgive my weird grammar or something.

**Comment by Rottengut** [comment]
Vickki Goldman and Juan Cruz in Hubologist HQ don't say anything too.

**Comment by Rottengut** [comment]
Percy in Gecko doesn't say anything.

**Comment by alexbatalov** [comment]
Hey, are using debug or release version?

**Comment by Rottengut** [comment]
> Hey, are using debug or release version?

I am using 1.0.3. release version

**Comment by Rottengut** [comment]
Solved in 1.1. Thanks!
