### ISSUE TITLE
[Android Release 1.0.3] Gruthat is missing

### ISSUE THREAD

**Issue by Rottengut** [alexbatalov/fallout2-ce#152]
Sorry for the typo. Gruthar is missing.

I am using Samsung Galaxy Tab S6.

In the first floor of Vault 13, there should be Gruthar. But I can't find him. I can find his son or other NPCs.

**Comment by alexbatalov** [comment]
Please post your savegame.

**Comment by Rottengut** [comment]
> Please post your savegame.

Is there a way to extract savegame on android?

**Comment by alexbatalov** [comment]
Depends on your Android version. Don't bother, I'll check one of mine.

**Comment by alexbatalov** [comment]
I've checked it. This is a very rare case, most likely scripting error (saving pointer as integer). It works in vanilla and reference edition because they don't make distinction between pointers and integers.
