### ISSUE TITLE
Fonline-Like HUD and Interface system

### ISSUE THREAD

**Issue by APAmk2** [alexbatalov/fallout2-ce#156]
Hi, I have an idea that will be useful to modders and the game as a whole, the idea is to add an interface system like in Fonline, you have a folder /data/art/intrface and it contains everything related to the interface, and next to it is an ini file containing settings in the format:
IFacePic=IFace.png
ButtonPic=Button.png
ButtonPicDn=ButtonDN.png
Button= x y x y Regarding IFacePic
InvenPic=Inven.png
InvenText=x y x y
This will make it easy to integrate new interfaces to modders, as well as allow to bring the existing interface to newer standards and make it more convenient

**Comment by IronKing24** [comment]
I believe Fonline uses "Dear ImGui" for its GUI implementation, implementing this framework here as with the case of SDL would allow for interface modularity I believe.
but allowing modders to use the framework directly would cause issues for beginner modders it should be integrated and obfuscated to be used with the scripting language.
