### ISSUE TITLE
Game crashes at the start

### ISSUE THREAD

**Issue by Adrian3345** [alexbatalov/fallout2-ce#159]
In old phones the apk crashes at the very start of the Game i wonder if there is any solutions?

**Comment by alexbatalov** [comment]
Your device and android version?

**Comment by Adrian3345** [comment]
> Your device and android version?

The Android versión it's 7.1.1 and it's called moto e (4) plus

**Comment by alexbatalov** [comment]
Sorry, I cannot reproduce your problem on the emulator. What game data are you using? Try English from GOG or the original CD version, make a new folder, copy only `master.dat` and `critter.dat`. Let me know the results.

**Comment by Adrian3345** [comment]
> Sorry, I cannot reproduce your problem on the emulator. What game data are you using? Try English from GOG or the original CD version, make a new folder, copy only `master.dat` and `critter.dat`. Let me know the results.

I have tried all of that before and it didn't work maybe it has to be something with the ram available or the cpu compatibilidad or maybe it has to be something with arm x32

**Comment by Adrian3345** [comment]
And other users have reported to me the same issue in discord it crashes at the start

**Comment by APAmk2** [comment]
Try Debug version, release is not working fine on most devices, i have that problem too

**Comment by Adrian3345** [comment]
> Try Debug version, release is not working fine on most devices, i have that problem too

Ok i i'm going to try it

**Comment by Adrian3345** [comment]
> Try Debug version, release is not working fine on most devices, i have that problem too

Hey but where it's the debug versión of the apk?

**Comment by Adrian3345** [comment]
> Sorry, I cannot reproduce your problem on the emulator. What game data are you using? Try English from GOG or the original CD version, make a new folder, copy only `master.dat` and `critter.dat`. Let me know the results.

I fixed the problem , i needed to use the debug apk and now it works fine thanks for your help 

https://user-images.githubusercontent.com/110355361/195992971-e4001407-a627-4bee-b98b-ea74bab5b274.mp4

**Comment by Adrian3345** [comment]
@alexbatalov hey it's posible a fallout 3 Port?

**Comment by alexbatalov** [comment]
It's never going to happen. The process to reverse engineer would be the same, but the numbers... Here is some math - Fallout 2 is about 4,000 functions, decompiling took about a year. Fallout 3 is about 60,000 functions, so yeah, that's 15 man-years of work.

**Comment by Adrian3345** [comment]
> It's never going to happen. The process to reverse engineer would be the same, but the numbers... Here is some math - Fallout 2 is about 4,000 functions, decompiling took about a year. Fallout 3 is about 60,000 functions, so yeah, that's 15 man-years of work.

Well that it's so sad i hope Bethesda makes a Port for android

**Comment by alexbatalov** [comment]
@Adrian3345 @APAmk2 Guys can you please check this apk if it works on your devices. This is a release version v.1.1.0 with cherry picked #187.
[app-release.apk.zip](https://github.com/alexbatalov/fallout2-ce/files/9867170/app-release.apk.zip)

**Comment by APAmk2** [comment]
Okay, i will check that and write result later

**Comment by APAmk2** [comment]
> @Adrian3345 @APAmk2 Guys can you please check this apk if it works on your devices. This is a release version v.1.1.0 with cherry picked #187. [app-release.apk.zip](https://github.com/alexbatalov/fallout2-ce/files/9867170/app-release.apk.zip 
Game crashes when try to load Arroyo temple enter map.

**Comment by alexbatalov** [comment]
Thanks, the bug is somewhere else.
