### ISSUE TITLE
Fallaout2-CE AmigaOS4 PowerPC Big Endian Port - Paths Problem

### ISSUE THREAD

**Issue by seventhwonder-amiga** [alexbatalov/fallout2-ce#161]
I am working on a AmigaOS4 (PowerPC Big Endian) SDL2 port of FallOut2-CE

I have succesfully compiled the executable, however I am still having paths related problems.

AmigaOS4 paths are like this:
PROGDIR:directory/directory

At its current states, compiled exe is looking for font files in "master.dat/font0."

Are the sources codes related to paths
platform_compat.cc?

Where should I make changes ?

**Comment by seventhwonder-amiga** [comment]
Here is the output from debug version. I attached some printf command

Excutable is looking for font 0 to font 9.. 
I extracted font.fon files from master.dat and there are only 5 fonts..


GameInıtWithOptions PAth:
 Sfall Config 2 Path:ddraw.ini
 Game Config File Path:fallout2.cfg
 XFileOpen filePath:font0.fon
 ---WE ARE AT PLATFORM_COMPAT.CC
 Compat_splitpath Path:font0.fon
Compat_splitpath Path:font0.fon
Compat_splitpath Drive:
Compat_splitpath Dir:Y
Compat_splitpath path:font0.fon
 XFileOpen filePath 4:font0.fon
 XFileOpen filePath 4:font0.fon
 XFileOpen filePath 4:font0.fon
 XFileOpen filePath 4:font0.fon
 XFileOpen filePath 4:font0.fon
 XFileOpen filePath 4:font0.fon
 XFileOpen filePath:font1.fon
 ---WE ARE AT PLATFORM_COMPACT.CC
 Compat_splitpath Path:font1.fon
Compat_splitpath Path:font1.fon
Compat_splitpath Drive:
Compat_splitpath Dir:Y
Compat_splitpath path:font1.fon
 XFileOpen filePath 4:font1.fon
 XFileOpen filePath 4:font1.fon
 XFileOpen filePath 4:font1.fon
 XFileOpen filePath 4:font1.fon
 XFileOpen filePath 4:font1.fon
 XFileOpen filePath 4:font1.fon
 XFileOpen filePath:font2.fon
 ---WE ARE AT PLATFORM_COMPAT.CC
 Compat_splitpath Path:font2.fon
Compat_splitpath Path:font2.fon
Compat_splitpath Drive:
Compat_splitpath Dir:Y
Compat_splitpath path:font2.fon
 XFileOpen filePath 4:font2.fon
 XFileOpen filePath 4:font2.fon
 XFileOpen filePath 4:font2.fon
 XFileOpen filePath 4:font2.fon
 XFileOpen filePath 4:font2.fon
 XFileOpen filePath 4:font2.fon
 XFileOpen filePath:font3.fon
 ---WE ARE AT PLATFORM_COMPACT.CC
 Compat_splitpath Path:font3.fon
Compat_splitpath Path:font3.fon
Compat_splitpath Drive:
Compat_splitpath Dir:Y
Compat_splitpath path:font3.fon
 XFileOpen filePath 4:font3.fon
 XFileOpen filePath 4:font3.fon
 XFileOpen filePath 4:font3.fon
 XFileOpen filePath 4:font3.fon
 XFileOpen filePath 4:font3.fon
 XFileOpen filePath 4:font3.fon
 XFileOpen filePath:font4.fon
 ---WE ARE AT PLATFORM_COMPACT.CC
 Compat_splitpath Path:font4.fon
Compat_splitpath Path:font4.fon
Compat_splitpath Drive:
Compat_splitpath Dir:Y
Compat_splitpath path:font4.fon
 XFileOpen filePath 4:font4.fon
 XFileOpen filePath 4:font4.fon
 XFileOpen filePath 4:font4.fon
 XFileOpen filePath 4:font4.fon
 XFileOpen filePath 4:font4.fon
 XFileOpen filePath 4:font4.fon
 XFileOpen filePath:font5.fon
 ---WE ARE AT PLATFORM_COMPACT.CC
 Compat_splitpath Path:font5.fon
Compat_splitpath Path:font5.fon
Compat_splitpath Drive:
Compat_splitpath Dir:Y
Compat_splitpath path:font5.fon
 XFileOpen filePath 4:font5.fon
 XFileOpen filePath 4:font5.fon
 XFileOpen filePath 4:font5.fon
 XFileOpen filePath 4:font5.fon
 XFileOpen filePath 4:font5.fon
 XFileOpen filePath 4:font5.fon
 XFileOpen filePath:font6.fon
 ---WE ARE AT PLATFORM_COMPACT.CC
 Compat_splitpath Path:font6.fon
Compat_splitpath Path:font6.fon
Compat_splitpath Drive:
Compat_splitpath Dir:Y
Compat_splitpath path:font6.fon
 XFileOpen filePath 4:font6.fon
 XFileOpen filePath 4:font6.fon
 XFileOpen filePath 4:font6.fon
 XFileOpen filePath 4:font6.fon
 XFileOpen filePath 4:font6.fon
 XFileOpen filePath 4:font6.fon
 XFileOpen filePath:font7.fon
 ---WE ARE AT PLATFORM_COMPACT.CC
 Compat_splitpath Path:font7.fon
Compat_splitpath Path:font7.fon
Compat_splitpath Drive:
Compat_splitpath Dir:Y
Compat_splitpath path:font7.fon
 XFileOpen filePath 4:font7.fon
 XFileOpen filePath 4:font7.fon
 XFileOpen filePath 4:font7.fon
 XFileOpen filePath 4:font7.fon
 XFileOpen filePath 4:font7.fon
 XFileOpen filePath 4:font7.fon
 XFileOpen filePath:font8.fon
 ---WE ARE AT PLATFORM_COMPACT.CC
 Compat_splitpath Path:font8.fon
Compat_splitpath Path:font8.fon
Compat_splitpath Drive:
Compat_splitpath Dir:Y
Compat_splitpath path:font8.fon
 XFileOpen filePath 4:font8.fon
 XFileOpen filePath 4:font8.fon
 XFileOpen filePath 4:font8.fon
 XFileOpen filePath 4:font8.fon
 XFileOpen filePath 4:font8.fon
 XFileOpen filePath 4:font8.fon
 XFileOpen filePath:font9.fon
 ---WE ARE AT PLATFORM_COMPACT.CC
 Compat_splitpath Path:font9.fon
Compat_splitpath Path:font9.fon
Compat_splitpath Drive:
Compat_splitpath Dir:Y
Compat_splitpath path:font9.fon
 XFileOpen filePath 4:font9.fon
 XFileOpen filePath 4:font9.fon
 XFileOpen filePath 4:font9.fon
 XFileOpen filePath 4:font9.fon
 XFileOpen filePath 4:font9.fon
 XFileOpen filePath 4:font9.fon
main function

**Comment by alexbatalov** [comment]
There is no need to extract data files from master.dat. The game attempts to load at most 10 old-style fonts (with `fon` extension) and at most 16 new-style fonts (`aaf`). At least one font of both styles should exist otherwise the game will fail to start with appropriate message. I'm not sure what's wrong with your code, fork this repo and push your changes so I can review.
