### ISSUE TITLE
[Android 1.1] Can't leave Broken Hills Mine

### ISSUE THREAD

**Issue by Rottengut** [alexbatalov/fallout2-ce#162]
I am using Samsung Galaxy Tab S6.

So I was doing Zaius' air purifier repair quest.

After repairing it, I couldn't find Exit Grid of the mine. Maybe I'm doing something wrong, but I couldn't find it.

Also, some of the speech options in Gecko's Power Plant EnclaveNet makes game to crash.

Edit: I think Broken Hills Mine issue was caused by not being able to scroll the screen enough. It could be a thing related to resolutions, but in my first playthrough this never happened.

**Comment by alexbatalov** [comment]
I cannot reproduce the mine exit problem (at least in Windows). Can you make a screenshot near the exit? I've noticed there are different scroll blockers near the exit. Make sure exit tunnel is in the bottom left part of the screen, then scroll down.
The crash in gecko is confirmed.

**Comment by Rottengut** [comment]
![Screenshot_20221003_190145_Fallout 2](https://user-images.githubusercontent.com/113081760/193551410-0bacdc6a-22d3-4390-8e27-467c02e3d30b.png)

![Screenshot_20221003_190157_Fallout 2](https://user-images.githubusercontent.com/113081760/193551447-9cd17eac-4e01-464e-9315-fae1f1066174.png)

**Comment by Rottengut** [comment]
> I cannot reproduce the mine exit problem (at least in Windows). Can you make a screenshot near the exit? I've noticed there are different scroll blockers near the exit. Make sure exit tunnel is in the bottom left part of the screen, then scroll down. The crash in gecko is confirmed.



> I cannot reproduce the mine exit problem (at least in Windows). Can you make a screenshot near the exit? I've noticed there are different scroll blockers near the exit. Make sure exit tunnel is in the bottom left part of the screen, then scroll down. The crash in gecko is confirmed.

![Screenshot_20221003_190145_Fallout 2](https://user-images.githubusercontent.com/113081760/193551618-d2e3a764-f71c-4dc6-a514-9df82f7aa039.png)
![Screenshot_20221003_190157_Fallout 2](https://user-images.githubusercontent.com/113081760/193551642-9c54e7b1-5a8c-46bb-91d2-0277a2b6a746.png)

**Comment by alexbatalov** [comment]
I guess there are badly positioned scroll blockers in effect when you're scrolling down. From this position scroll to the right - make sure your character is in left bottom of the screen - then scroll down.

**Comment by Rottengut** [comment]
> I guess there are badly positioned scroll blockers in effect when you're scrolling down. From this position scroll to the right - make sure your character is in left bottom of the screen - then scroll down.

I might be doing something wrong but... it doesn't work..

**Comment by alexbatalov** [comment]
Ok, check the screenshots below. They are from Windows but the same problem is easily reproducible.

This is the one where you are currently standing. This is the left-bottom corner of the map (you cannot scroll left or down).
![bad](https://user-images.githubusercontent.com/172978/193561015-9e2c3e2c-3fa3-4081-ab5d-93722c28c3b4.png)

From the position above scroll to the right. After that you'll be able to scroll down a few tiles (which is enough to see exit grid).
![good](https://user-images.githubusercontent.com/172978/193561359-2273f925-2a16-457e-86f9-c5ccec0197f2.PNG)

**Comment by Rottengut** [comment]
> 

I know it sounds really idiotic.. but it doesn't work for me. 

After scrolling screen to the bottom left, I scrolled to the right. But I cannot scroll down after that.

I think I'd just have to use another save game.

**Comment by alexbatalov** [comment]
I was able to replicate you problem. Turn off `IFACE_BAR_MODE` in your `f2_res.ini`. Interface bar is floating right on top of the exit grid.
