### ISSUE TITLE
Linux port

### ISSUE THREAD

**Issue by JanSimek** [alexbatalov/fallout2-ce#17]
The project compiles and runs under linux after some changes and commenting out the audio code. Below is the list of functions and macros that need to be reimplemented for linux:

- [x] `_splitpath`
- [x] `filelength`
- [x] `stricmp` → alias to `strcasecmp`
- [x] `strnicmp`
- [x] `strupr`
- [x] `strlwr`
- [x] `itoa`
- [x] `CopyFileA`
- [x] `timeGetTime`
- [x] `GetTickCount`
- [x] `min` → macro `#define MIN(a, b)  (((a) < (b)) ? (a) : (b))`
- [x] `max` → macro `#define MAX(a, b)  (((a) > (b)) ? (a) : (b))`
- [x] `_MAX_DIR` → ?
- [x] `_MAX_FNAME` → `FILENAME_MAX`
- [x] `_MAX_EXT ` → ?
- [x] `MAX_PATH` → `PATH_MAX` 

Also, what about the mutexes? I don't understand what the autorun.c/h file is for except preventing multiple instances of the game being run.

**Comment by Risu** [comment]
For help with audio you can take a look at falltergeist implementation: [Mixer.cpp](https://github.com/falltergeist/falltergeist/blob/develop/src/Audio/Mixer.cpp)

**Comment by k3tamina** [comment]
> Also, what about the mutexes? I don't understand what the autorun.c/h file is for except preventing multiple instances of the game being run.

Aside the fact that [a Windows mutex is not a mutex](http://www.sevangelatos.com/a-windows-mutex-is-not-a-mutex/) but is instead an interprocess sync primitive, I think that they are being used:
1. in `autorunMutexCreate` to prevent multiple instances of the same process, mutex is freed at the end of `falloutMain` by calling `autorunMutexClose`
2. in `programWindowSetTitle` to prevent multiple initialization of the window title, mutex is freed in `windowManagerExit` being called twice by calling `gameExit > _windowExit` at the end of `falloutMain` and redundantly at exit by calling `atexit(windowManagerExit)` in `windowManagerInit`
3. in `main` but freed almost immediately in `windowManagerInit`, I don't understand why

To make number 1 cross platform I think the most effective way it to implement file locking, either by using a well maintained library (such as [boost](https://www.boost.org/doc/libs/1_79_0/doc/html/interprocess/synchronization_mechanisms.html#interprocess.synchronization_mechanisms.file_lock)) or by hardcoding for each platform ([linux example](https://stackoverflow.com/questions/5339200/how-to-create-a-single-instance-application-in-c-or-c/5339606#5339606))

In my opinion number 2 shouldn't be needed, it can be replaced by introducing well thought global variables.
Number 3 might not be needed, until we figure out what's it needed for.

**Comment by alexbatalov** [comment]
I don't think we need them at all. I've checked a couple of open source games, there are no locks or mutexes to prevent multiple instances.
