### ISSUE TITLE
Russian translation not workin on ios version 

### ISSUE THREAD

**Issue by Motherfuckre** [alexbatalov/fallout2-ce#170]
I used same cache with russian translation from my android device, but on ios russian fonts are completely messed up. Voiceover not working either.
![4A36FBCD-D100-4DEE-810A-AAFD0BA781A8](https://user-images.githubusercontent.com/115837266/195973179-99b2a255-a388-4cd0-9443-b8dda60196f6.png)

**Comment by alexbatalov** [comment]
Paths handling is still crappy in the engine. Look at the your `data` directory, make sure your font files are all lowercased, e.g. `font0.aaf`, `font1.aaf`, `font2.aaf`. The same for `fon` files.

**Comment by Motherfuckre** [comment]
Yeah, that seemed to help. Thanks
