### ISSUE TITLE
How to run Fallout Nevada

### ISSUE THREAD

**Issue by seadra** [alexbatalov/fallout2-ce#177]
Hi,

Apologies for the newbie question, but how can I run Fallout Nevada with Fallout 2 CE?

I installed Fallout Nevada (Extended) from [here](https://www.nma-fallout.com/threads/fallout-nevada-extended.207311/), and tried installing it to the root directory of Fallout 2 (from steam), using wine on Linux. I also tried to install into the subfolder "Nevada Mod (Extended)". I then copy-pasted the fallout2-ce executable into the mod's folder.

When I try to run fallout2-ce, I get the following error:

"Couldn't find/load text fonts"

which also creates an empty folder "master.dat". I tried removing the empty "master.dat" and replacing it with the one from the original game. When I run fallout2-ce, it shows the game screen which says "Please Standby" and then game quits without any messages.

**Edit:** I copied a working Fallout Nevada installation over from Windows, which works on Wine, but unfortunately, same results with fallout2-ce.

The vanilla Fallout 2 does work BTW, thanks a lot for the efforts in making this portable version a reality!

**Comment by seadra** [comment]
I copied the master.dat and critter.dat from the original game to the Fallout 2/Nevada Mod (Extended)/ folder. After renaming Patch00[01].dat to patch00[01].dat, it sort of works: the initial map shows fine. The videos that get displayed are not Fallout Nevada videos though, they're instead the original Fallout 2 videos.

**Comment by bouncingbenji** [comment]
So dose copy over fallout 2 or add a separate game so you have 2?? Or can u still play fo2 and this is just extra mission

**Comment by seadra** [comment]
If I'm understanding you correctly, I made a copy of the original Fallout 2 folder, so there are two copies of the game: one is the original Steam folder, and the other folder is the one with Nevada.

**Comment by bouncingbenji** [comment]
So is there 2 app icons? That's what I was getting at sorry
