### ISSUE TITLE
Crash in Fallout Nevada

### ISSUE THREAD

**Issue by seadra** [alexbatalov/fallout2-ce#178]
This happens at the beginning of the game: gathered the party, went outside, collected the data to holodisk, and went back inside. The game crashed about 5 seconds after the end of the cinematic that said the year is now 2140 ended and the game started in a vault with the player in a black suit, with the following message:

```fallout2-ce: /home/user/src/fallout2-ce/src/interpreter.cc:1131: void fallout::opConditionalOperatorLessThanEquals(Program*): Assertion `false && "Should be unreachable"' failed.```

Also, not sure if this is relevant or not, but I'm seeing debug messages like the following:
```
Script Error: scripts\VbCCmndr.int: op_tile_num: obj is NULL
Script Error: scripts\VbCCmndr.int: op_obj_can_see_obj: obj is NULL
```

(Could this be caused by the case-sensitive file system?)

**Comment by seadra** [comment]
I checked the value of `value[1].opcode` in `opConditionalOperatorLessThanEquals` which caused the assertion: it is `0xE001` which seems to be `VALUE_TYPE_PTR` in interpreter header file.

Adding

```c++
    case VALUE_TYPE_PTR:
        switch (value[0].opcode) {
            case VALUE_TYPE_INT:
                result = (intptr_t)value[1].pointerValue <= (intptr_t)value[0].integerValue;
                break;
            default:
                assert(false && "Should be unreachable");
        }
        break;
```
as the last case before `default` in `opConditionalOperatorLessThanEquals` fixed the crash.

**Comment by alexbatalov** [comment]
Thanks
