### ISSUE TITLE
Game performace tanks on android after minimizing and recovering

### ISSUE THREAD

**Issue by KoleckOLP** [alexbatalov/fallout2-ce#183]
the game performace is good if you launch the game and play,
but if I minimize the game and recover it
the perfomace is much worse.

my device POCO F3 Android 12

video showcasing it
https://www.youtube.com/watch?v=Gg5BTK8Go2s

**Comment by sonilyan** [comment]
I think alexbatalov already resolve this problem, you need wait for next release

**Comment by alexbatalov** [comment]
@KoleckOLP Please check one of debug builds from the "Actions" tab, this problem is already solved. Reopen if not. Thank you.

**Comment by bouncingbenji** [comment]
Ot works fine on my s21

**Comment by KoleckOLP** [comment]
Works fine for me too now.
