### ISSUE TITLE
World map: doesn't redraw the whole screen, Dude can sometimes still be seen

### ISSUE THREAD

**Issue by Janiczek** [alexbatalov/fallout2-ce#193]
<img width="1624" alt="bug-report-map-redraw-dude" src="https://user-images.githubusercontent.com/149425/199012963-364ad559-e40e-4079-b9cd-cec03e33a690.png">

I don't have a save for this (sorry), but it seems that when you have a non-default screen resolution (in my case 1512x800), the game doesn't draw black over the whole map area and the Dude can still be seen if he was outside the world map rectangle.

(The interface bar also probably shouldn't be shown, right?)

(I guess the real fix would be to expand the world map area to fill the whole screen.)

**Comment by APAmk2** [comment]
That post is not really answer for you question, but i have one good idea, if Alex want, he will can add fullscreen maps like addition for HRP, i have some Fonline variations, but they need to little edited for singleplayer, i can do this if he will asking me for that. For example i can post this, that is old screenshot from internet
![xbztq.jpg](https://user-images.githubusercontent.com/107351397/209856387-16e0467d-55d7-40e7-8a76-03d2b0574ffa.jpg)

**Comment by alexbatalov** [comment]
Hey, I don't know how Fonline works. For various resolutions the image is usually should be sliceable to 9 parts with centre segments stretchable or which can be tiled (so the image should be accompanied by metadata).
