### ISSUE TITLE
Краш при путешествии по миру на машине

### ISSUE THREAD

**Issue by SERAPHIMVDK** [alexbatalov/fallout2-ce#210]
Логи предоставить не могу ибо их попросту нет. Но проблема такая, при путешествие по миру на машине игра просто вылетает. и спасает только пешее путешествие

**Comment by APAmk2** [comment]
Андроид? Ты можешь достать логи через ADB, сейчас поищу, мне где-то разработчик давал способ

**Comment by APAmk2** [comment]
`adb logcat | findstr com.alexbatalov.fallout2ce`
Команда которую надо ввести, сначало запусти игру, схвати ошибку и запусти команду, потом скопируй вывод консоли в файл и отправь сюда

**Comment by SERAPHIMVDK** [comment]
Я уже апк обновил вроде пока пропал краш с вылетом
