### ISSUE TITLE
fallout 1

### ISSUE THREAD

**Issue by SERAPHIMVDK** [alexbatalov/fallout2-ce#211]
Будет ли реализован первый фолыч? И некий старый "высер" как fallout tactics?

**Comment by APAmk2** [comment]
Тактикс это другой движок и изометрия (в ф2 триметрия), а для Fallout 1 есть мод fallout et tu

**Comment by Vic2077** [comment]
Вот только не надо гнать на Тактикс. Вполне себе норм игра, и графон там хорош. Хоть это уже и не РПГ а больше тактическая стратегия, или я хз, как этот жанр называется. А вот поддержку первого Фоллыча, модов на второй, и Олимпа 2207 видеть бы хотелось, да.
И да, Если у тебя в телефоне процессор ARMv8, то есть другое приложение для запуска 2 и 1 Фоллыча и многих модов на второй (fo2.exe называется), и в будущем там даже планируется добавить поддержку Тактикса, вроде как.

**Comment by APAmk2** [comment]
Ты наркоман штоле сукко? Я говорил про то что тактикс это первое ДРУГОЙ ДВИЖОК, а второе ДРУГОЙ ВИД ПРОЕКЦИИ, как ты его собрался тут запускать?

**Comment by APAmk2** [comment]
> А вот поддержку первого Фоллыча, модов на второй, и Олимпа 2207 видеть бы хотелось, да.
Поддержка модов для Fallout 2 без SFall уже есть и они спокойно запускаются

**Comment by alexbatalov** [comment]
Fallout 1 - yes, as very similar, but separate project. Tactics - no, at least not by me (with 14k functions and no symbols it needs 3-4 man-years of work).

This project is capable of running original Nevada and Sonora (they do not depend on Sfall, I'm not sure about more recent "fixed", "crazy", and other versions of those mods which circulate on various forums), although there might be some bugs. Olympus is partially supported.

**Comment by APAmk2** [comment]
Crazy and fixed editions is containing sfall, but like add-on, so running fixed edition files technically available, but im not sure

**Comment by cecxl** [comment]
What about Arcanum? also written by Cain unlike Tactics.

**Comment by APAmk2** [comment]
OTHER ENGINE AND GRAPHICS, DON'T ASK STUPID QUESTIONS

**Comment by alexbatalov** [comment]
I haven't checked Arcanum, with F1 and IWD2 in progress I simply don't have time and resources to maintain so many projects.

**Comment by JanSimek** [comment]
I will contribute one more stupid question. Is the lua scripting still on table?

**Comment by alexbatalov** [comment]
Yes, in fact I've already got it working on one of my private branches. I've decompiled vanilla .int files to .lua, so most of the game should work, but both engine and especially lua scripts will need extensive review (with ~1500 scripts and 800k SLOCs it will be pretty time consuming).

**Comment by Vic2077** [comment]
I'm also up for Arcanum and Tactics on mobile, but yes, too much work. You need a team for that (I wouldn't mind to wait a few years for that, though. I mean, we've waited for ~25 years for this, 5 or so years more won't change much - of course, if we'll live long enough, but this is a different question, haha. And in 5 years I might get a new device with ARMv8 CPU and will be able to run FO2.exe so... whatever. I don't look THAT far in the future these days...)
