### ISSUE TITLE
НАЭКРАННОЕ УПРАВЛЕНИЕ

### ISSUE THREAD

**Issue by SERAPHIMVDK** [alexbatalov/fallout2-ce#212]
Будет ли реализована отрисовка управления. И будет ли оно вообще? Или так и останется 2-3 тапа по экрану?

**Comment by APAmk2** [comment]
Не думаю, возможно кто-то решит проблему просто сделав форк и запилив функционал, но не сейчас

**Comment by alexbatalov** [comment]
Eventually it will, but it's not the priority at this time.

**Comment by SERAPHIMVDK** [comment]
Если это на данном этапе можно реализовать то сделайте что бы 1 клик это было нажатие а 2 клика это смена курсора на ходьбу и атаку

**Comment by APAmk2** [comment]
Разработчик где-то писал что это сделано для исключения мисскликов

**Comment by SERAPHIMVDK** [comment]
![Screenshot_2022-12-27-23-21-35-10_044a0293e07d68fc30c3800cb1368b1b](https://user-images.githubusercontent.com/35951845/209675772-3a49d8a3-48e6-491d-b4bf-16ccbd5ae5a0.png)
Было бы отлично увидеть так)
