### ISSUE TITLE
Wgen is the next Update coming out if there is going to be one? If so is going to be a big to complete with fo2.exe as you can play 4 fo games on that one? 

### ISSUE THREAD

**Issue by bouncingbenji** [alexbatalov/fallout2-ce#213]

**Comment by APAmk2** [comment]
1.Update will be coming as fast, as Alex can
2.that is Re-engineered engine, fo2.exe is just wine with additional features specifically made for Fallout, difference in them that is Fo2.exe is just win-interpreter, in same time F2-RE is native engine

**Comment by bouncingbenji** [comment]
I bet everything you said is awesome but I'm not a tech guy just happy that I can play it on my android, I've not really looked in to the difference between them and I'd love to give money to Alex or how ever us working on it....thank you xx

**Comment by alexbatalov** [comment]
I plan to release next version early in January, and then once per one-two months depending on the progress. I didn't get your question about f2.exe, please elaborate.

**Comment by Vic2077** [comment]
> I plan to release next version early in January

Please, add alternative touchscreen controls (2 handed, so it will be possible to click interface buttons directly) and Keyboard support (to enter the Character / Savegame name) to the next release. I think that'll be enough for me to start actually playing. (I can't change cursor type with default control scheme intentionally, only sometimes by chance, when I'm randomly tapping all over the screen like a mad woodpecker, and the debug build with keyboard support refused to playbackground music on my device, while on the more early builds the music was playing just fine.)

**Comment by SERAPHIMVDK** [comment]
Вик2077 Я этот вопрос задавал уже, покопавшись я так и не смог сделать отрисовку кнопок управления так как игра изначально придумана для мышки. Если автор порта решит сделать тач то хорошо но сейчас пройдя полностью fallout 2, могу сказать управление по началу конечно будет странным, но со временем привыкнешь. Управление щас далеко не в приоритете. А с клавиатурой давно решён вопрос

**Comment by APAmk2** [comment]
@bouncingbenji You are received answers? Can you close issue? Thanks.
