### ISSUE TITLE
Fallout 2 HIGH RESOLUTION PATCH

### ISSUE THREAD

**Issue by SERAPHIMVDK** [alexbatalov/fallout2-ce#215]
будет ли поддержка данного патча ибо для телефонов с 2к разрешением очень бы помогло

**Comment by SERAPHIMVDK** [comment]
Ещё раз пройдя игру я хочу показать с чем можно столкнуться. Хоть это и классическая ошибка из за того что изначально игра шла на квадратные моники. Но в будущем может быть реализован встроенный фикс данной проблемы которую как раз таки и убирает патч высокого разрешения
![Q9L0fhYVbu8](https://user-images.githubusercontent.com/35951845/210175269-088af178-929c-4561-9476-6864e1a7c45f.jpg)
![B-SvBiwAAxU](https://user-images.githubusercontent.com/35951845/210175266-7bcb2926-52f4-48e9-afd7-4e731a258236.jpg)

**Comment by alexbatalov** [comment]
I'm aware of issues on your screenshots. If you know something else is missing from HRP please post it in #3.

**Comment by SERAPHIMVDK** [comment]
![8DzSiLWhqb8](https://user-images.githubusercontent.com/35951845/210214164-d527357a-7170-4246-9f3f-369886759a2d.jpg)
Здесь игрок видит то чего не должно быть, а именно края карты. Ну и панель по краям чёрная

**Comment by SERAPHIMVDK** [comment]
Ну а тут проблема всё так же с отображением. Но вот с картой есть 2 делемы. 1 Проблемма. Нельзя дивать влево и вправо. Только вверх и вниз. И есть баг с текстурой на странице городов
![qWZWUUuBRS0](https://user-images.githubusercontent.com/35951845/210214391-3058dcb8-33e6-4bb0-9132-cdb3b81dfec1.jpg)

**Comment by SERAPHIMVDK** [comment]
С титрами вопрос решён. Но так же остались проблемы которые указаны на других скринах. Можете сделать так что бы по краям был просто тёмный фон для карты, видео вставок.
![wKdkT3yI1lw](https://user-images.githubusercontent.com/35951845/210226444-6756fa1f-3ce1-4ec0-8b44-9f66fea8e11d.jpg)

**Comment by SERAPHIMVDK** [comment]
Всё отлично но вот с картой как быть? видео по ссылке. В лево и В право нет движения никакого
https://www.youtube.com/watch?v=GUtaj-aUPts

**Comment by c6-dev** [comment]
Попробуйте в f2_res.ini:
```
;if IFACE_BAR_SIDE_ART=0 - Black, No Iface-bar side art used.
;if IFACE_BAR_SIDE_ART=1 - Metal look Iface-bar side art used.
;if IFACE_BAR_SIDE_ART=2 - Leather look Iface-bar side art used.
IFACE_BAR_SIDE_ART=1

**Comment by SERAPHIMVDK** [comment]
c6-dev результата никакого к сожалению

**Comment by SERAPHIMVDK** [comment]
![YBOzBe_7a-M](https://user-images.githubusercontent.com/35951845/210240372-5109011a-7de6-4ef6-b1aa-707304682c9e.jpg)
Чего то я переборщил)

**Comment by SERAPHIMVDK** [comment]
единственное что помогло убрать полосы так это
; if IFACE_BAR_MODE=0 - the bottom of the map view window sits at the top of the IFACE Bar.
; if IFACE_BAR_MODE=1 - the bottom of the map view window extends to the base of the screen and is overlapped by the IFACE Bar.
IFACE_BAR_MODE=0

**Comment by SERAPHIMVDK** [comment]
ибо не отрисовывается текстура по краям

**Comment by APAmk2** [comment]
У тебя должен стоять контент HRP, он не интегрирован

**Comment by SERAPHIMVDK** [comment]
> У тебя должен стоять контент HRP, он не интегрирован

я через пк пропатчил. Но пока результат только такой

**Comment by SERAPHIMVDK** [comment]
Сделать так, что бы HRP был в самом APK,

**Comment by APAmk2** [comment]
В движке уже есть функции HRP, у тебя нет графики для него, тебе нужно чтобы она тебя уже была

**Comment by SERAPHIMVDK** [comment]
Хорошо, как мне получить графику для HRP?

**Comment by APAmk2** [comment]
Просто ставишь Fallout 2 на пк, поверх него HRP и после делаешь всё тоже, что и когда ставил на телефон

**Comment by SERAPHIMVDK** [comment]
Самое странное что у меня с уже пропатченая hrp версия

**Comment by APAmk2** [comment]
Тогда странно, контент у тебя уже должен быть, значит ничего делать не надо, хотя если хочешь убедиться - делай

**Comment by SERAPHIMVDK** [comment]
Я попробую переустановить и перекинуть по новой ресы. Если не получиться то скорее всего ошибка будет со стороны порта я думаю

**Comment by SERAPHIMVDK** [comment]
Я щас по новой перекачал фолыч накинул патч, проверил на пк. Он работает, на телефоне шишь с маслом.

**Comment by SERAPHIMVDK** [comment]
это могут быть лишь догадки но может это связанно с недоделанным Sfall?
;Set the number of colours here
; 8 for 8bit colour output (original)
; 16 for 16bit colour output (set only if your not using Sfall with graphics modes 4 or 5)
; 32 for 32bit colour output (set only if your not using Sfall with graphics modes 4 or 5)
COLOUR_BITS=32

**Comment by alexbatalov** [comment]
At this time CE does not load any custom `dat` files. However it can load unpacked HRP stuff - wide interface bar (`hr_iface_800.frm`), left/right side panels (`hr_ifacelft1.frm`, `hr_ifacerht1.frm`) from your `data` directory. This is a work in progress.

`COLOUR_BITS` is meaningless in CE. Output format and conversion from 8-bit images are managed automatically by SDL.
