### ISSUE TITLE
Лаунчер

### ISSUE THREAD

**Issue by SERAPHIMVDK** [alexbatalov/fallout2-ce#216]
Будет ли в будущем реализован лаунчер для выбора тех же самых настроек разрешения, модов, выбора доп функций или же к примеру выбора части fallout(если в будущем будет портирован 1 фолыч)

**Comment by SERAPHIMVDK** [comment]
Просто мы реализовали подобное давно. Для игр на движке valve, хочу узнать будет ли подобное?
![9ORbBnXmcaw](https://user-images.githubusercontent.com/35951845/210225733-995bff9b-9041-44da-b160-c709c1ed0e9c.jpg)

**Comment by APAmk2** [comment]
Смысл в выборе части если у F1 и F2 один и тот-же движок, но разных версий? Достаточно будет запила функций необходимых для запуска.
Доп. функции будут лишь когда будет полностью внедрён SFall, сейчас их попросту нет.

**Comment by SERAPHIMVDK** [comment]
По этому я и спрашиваю, будет ли подобное реализовано.
