### ISSUE TITLE
Проблема с торговлей

### ISSUE THREAD

**Issue by SERAPHIMVDK** [alexbatalov/fallout2-ce#217]
![Screenshot_2023-01-04-11-02-14-48_044a0293e07d68fc30c3800cb1368b1b](https://user-images.githubusercontent.com/35951845/210465790-8cf15ec4-a715-46fb-94c9-46e12f5a20a9.jpg)
Во время торговли есть возможность только нажать на кнопку всё. Надо сделать как на ПК, что бы можно было вводить с клавиатуры сколько чего надо. Здесь тоже надо реализовать появление Клавы во время допустим предложения определённого количества крышек

**Comment by APAmk2** [comment]
Кнопки плюс и минус справа от числа не думаешь что активны и нужны для чего-то?

**Comment by SERAPHIMVDK** [comment]
тоесть ты предлагаешь мне по кнопкам считать допустим 3451 крышку?
такое проще на клаве написать

**Comment by APAmk2** [comment]
Тоесть я предлагаю зажать одну из кнопок и активировать ускоренный "счёт" и потом уже скорректировать одиночными нажатиями.

**Comment by SERAPHIMVDK** [comment]
Я понял про что ты, я имею в виду что это довольно долго будет производиться.
