### ISSUE TITLE
Game make device turn off [ANDROID]

### ISSUE THREAD

**Issue by 0Mikeehrmantraut0** [alexbatalov/fallout2-ce#218]
Hello I have a Asus ROG phone 5 and while I play it reboot my phone , i have try to clean cache files but it seem to still doing this how can I fix that , thanks you

**Comment by alexbatalov** [comment]
These reboots happen randomly or when you're doing something specific (clicking, speaking, trading, inventory, movies, worldmap)? How long can you play before reboot?

**Comment by 0Mikeehrmantraut0** [comment]
> 

I would say 3-4 min around the time to made character enter in temple and fights first ants

**Comment by alexbatalov** [comment]
If you're using release version, try debug.

**Comment by 0Mikeehrmantraut0** [comment]
> If you're using release version, try debug.

Where can I get the debug ?

**Comment by 0Mikeehrmantraut0** [comment]
> Under "Actions" tab, select last workflow run, scroll down to "Artifacts" section.

I will try this thanks you

**Comment by 0Mikeehrmantraut0** [comment]
> Under "Actions" tab, select last workflow run, scroll down to "Artifacts" section.

Debug version seem to work , i will try to continue game but I would like know how can I change language, by default is the fallout.cfg who put the default language but there without 🤔

**Comment by alexbatalov** [comment]
Probably the same memory alignment issue (#122) with more severe consequences. To change your language look for `fallout2.cfg` in the game directory.

**Comment by 0Mikeehrmantraut0** [comment]
> Probably the same memory alignment issue (#122) with more severe consequences. To change your language look for `fallout2.cfg` in the game directory.

Hello I have try to change language by putting the cfg into folder and reinstall the app but it just have deleted my save 😞

**Comment by alexbatalov** [comment]
Fixed in 2714dc1ea14b3786e28be3a631bae0dd43fe3b8f.
