### ISSUE TITLE
No in-game music. iPhone iOS 16.2

### ISSUE THREAD

**Issue by mmrx48** [alexbatalov/fallout2-ce#219]
Hi! In-game music is completely absent. But the other sound works great! In the game settings, the volume of the music is set to full, but I can not hear it. How to solve this problem?

**Comment by SERAPHIMVDK** [comment]
у меня всё решилось что на ios что на android просто раз перезапустив игру

**Comment by mmrx48** [comment]
@SERAPHIMVDK, да игру-то до этого перезапускал не один раз. Звуков музыки так и не услышал, этого божественного эмбиента((( Попробую на досуге другую версию игры установить, может в этом проблема, т.к. у меня стоит локализованная от 1С.

**Comment by mmrx48** [comment]
But I didn’t see an elephant... In the 1C localization that I found, there is no music at all. I took the `sound` folder from another release, a miracle happened - everything worked!
