### ISSUE TITLE
Running on a Raspberry pi4

### ISSUE THREAD

**Issue by Exarkuniv** [alexbatalov/fallout2-ce#223]
First off i have to say this project is amazing. im so excited to have fallout 2 working without wine. and how easy it was for me to get this working on my Pi4. 
Im running this on Retropie, i made a install script to easily install it 

this is more some questions then a issues

does this work with fallout 2 restoration project?

is there a way to increase the resolution of the game, some of the words are not very clear

and other then using dosbox or wine, is there a project out there for fallout 1 similar to this one. so i dont have to use dosbox or wine to play fallout 1

**Comment by alexbatalov** [comment]
1. RP is not yet supported. It uses many Sfall scripting functions, which are not yet implemented. I guess Olympus is going to be supported next, then RP, then Ettu (this progression is based solely on number of scripting functions used). Meanwhile you can try Nevada and Sonora.
2. The minimum resolution is 640x480 (as many in-game art have this size). You can configure resolution via `f2_res.ini`. but it also affects window size (when running in windowed mode). I guess what you're asking for is scaling this resolution to a larger window size, so everything appears enlarged. This is on the roadmap.
3. I've released [Fallout Reference Edition](https://github.com/alexbatalov/fallout1-re) today. Once completed and tested, it will be used as base for Community Edition.

**Comment by Exarkuniv** [comment]
Very cool. im loving this. i will play around with Nevada and Sonora
thank you for all your guys hard work. 

i will play around with the ``f2_res.ini`` and see what i like or not. 
great news about the Fallout Reference Edition. it will be very cool to have Fallout working with out dosbox or wine.

**Comment by arrowgent** [comment]
good news,

fo1-ce & fo2-ce both compile and run successfully on a raspberry pi 4b using 32bit raspbian debian 11 (armhf)

thanks
