### ISSUE TITLE
V. 1.2 for Mac does not launch

### ISSUE THREAD

**Issue by sdlotu** [alexbatalov/fallout2-ce#226]
I have downloaded the GameData folder from the original CD into a new folder(Fallout 2 CE). I then downloaded and copied fallout2-ce for Mac into the Fallout 2 CE folder.

I launch the game and an error pops up a window: Couldn't find/load text fonts.

The only option is to click OK, and when i do so, the game quits.

**Comment by alexbatalov** [comment]
Hey, please check #134. Let me know if that didn't help.

**Comment by sdlotu** [comment]
Thanks for the prompt response. I am new to Git and did not know how to search for this issue. The game now launches and runs as expected.

To avoid this issue in the future, may I respectfully suggest you change the instructions for Mac on the readme to say:

"Copy **just the contents of** the GameData folder somewhere, for example /Applications/Fallout2."

This way, the person installing the files will know NOT to just copy the GameData folder to the destination folder.

**Comment by sdlotu** [comment]
Tested more thoroughly and am satisfied this can be closed.

**Comment by sdlotu** [comment]
Sorry, mis-clicked.

**Comment by sdlotu** [comment]
Closing
