### ISSUE TITLE
improvement suggestion for android

### ISSUE THREAD

**Issue by CrashBooms** [alexbatalov/fallout2-ce#227]
On android fallout run not in full screen, how about add quick button like start/end fight, quick save/load, sneak, lockpick, etc..

**Comment by APAmk2** [comment]
Engine running not in fullscreen because you haven't set proper resolution in config file. Control issues now is not prior thing.

**Comment by Nelorio12** [comment]
> Engine running not in fullscreen because you haven't set proper resolution in config file. Control issues now is not prior thing.

How do you set proper resolution in the config file? Is it on f2_res.ini or fallout2.cfg? because none of those work.

**Comment by Nelorio12** [comment]
Ok I found it, you must adjust resolution on the android folder itself. Look for "com.alexbatalov.fallout2ce" folder then look for ddraw.ini then open notepad. Set the game mode to 4 and try using 1920x1020. You could try tinkering f2_res.ini as well and pick a resolution of choice.

**Comment by APAmk2** [comment]
@CrashBooms Can you close issue, please?

**Comment by CrashBooms** [comment]
Oops sorry, done

**Comment by CrashBooms** [comment]
Oops sorry, done
