### ISSUE TITLE
Is it possible to use Fallout 2 Restoration project mod with fallout2-ce?

### ISSUE THREAD

**Issue by Shokklicht** [alexbatalov/fallout2-ce#229]
At least this installation did not work https://github.com/BGforgeNet/Fallout2_Restoration_Project/blob/master/docs/linux.md

Anybody been more successful?

**Comment by alexbatalov** [comment]
Hey, RP is not yet supported. It uses many Sfall features which are not yet implemented. I'm currently busy with finishing Fallout 1 Community Edition (coming later this week). Once completed and initial bugs are fixed, I'll return to integrating Sfall. There is no ETA at this time.
