### ISSUE TITLE
[Sonora] Cant continue game

### ISSUE THREAD

**Issue by APAmk2** [alexbatalov/fallout2-ce#231]
I would to help the project, so i started testing some mods and new builds of engine in android and PC. I installed sonora and that is running properly on previous release. But on new release when i trying to talk Grandma Andocia - game is crashing. And i couldn't download latest debug builds because they deprecated, but i can test that builds if someone will provide it.
Using vanilla Sonora 1.10 without SFall and any other mods.

https://user-images.githubusercontent.com/107351397/217842294-ff5b3f2f-1b43-4f03-8305-8795006cff82.mp4

**Comment by APAmk2** [comment]
Android crash, captured by scrspy, and logcat output
[output.txt](https://github.com/alexbatalov/fallout2-ce/files/10698373/output.txt)

https://user-images.githubusercontent.com/107351397/217845885-121b9f22-d5b4-4a93-a8ee-7db448d7519b.mp4

**Comment by alexbatalov** [comment]
Hey, that's great, both Sonora and Nevada needs testing. You can test on any platform, don't forget to mention which.  It's much simpler to test on desktops (providing savegames is easier and installing updates is faster).
