### ISSUE TITLE
[Sonora] Dialog window is freezing at screen

### ISSUE THREAD

**Issue by APAmk2** [alexbatalov/fallout2-ce#232]
If you talk with that kid and ask him to follow you - dialog window will be closed, but graphics will be freezed at screen, input and other controls will works normally, and save reloading and re-enter to location doesnt take any effect, you need to restart game for fixing that.
And of course, as you can see - scrollblockers doesnt wokrs, Sonora Devs is placed special red lines objects in mapper, that displays actual scrollblockers position, that is only quality-of-life objects, they using normal scrollblockers in maps.
Using latest debug build.

https://user-images.githubusercontent.com/107351397/217904775-549a9f0f-f9d4-4bb9-933c-37ee1347796a.mp4

**Comment by alexbatalov** [comment]
Looks like scripting error. Post your savegame so I can check.

**Comment by APAmk2** [comment]
[SLOT06.zip](https://github.com/alexbatalov/fallout2-ce/files/10703786/SLOT06.zip)

**Comment by APAmk2** [comment]
Also i meet that when trying to buy beer for all in Garage-city.
[SLOT05.zip](https://github.com/alexbatalov/fallout2-ce/files/10703819/SLOT05.zip)

**Comment by APAmk2** [comment]
I finded one detail with that bugs. That happening when someone taking from you something in dialog, maybe that will be helpful.
