### ISSUE TITLE
Data collection

### ISSUE THREAD

**Issue by V01DZ3R0** [alexbatalov/fallout2-ce#233]
Hi, with that cross-platform potential, could you add paragraph for used compilators for each (or at least windows for now) build  version in readme? And a little how-to-make guide would be nice, too. I am willing to help with it, if you agree.

**Comment by alexbatalov** [comment]
Hey, thanks for your interest in F2CE.

If you just want to compile it yourself, it's better to follow build steps from [ci-build.yml](../blob/main/.github/workflows/ci-build.yml) workflow, they are pretty straightforward. If you'd like to setup dev environment, well, it depends on your IDE. I'm using VS Code as my main tool, but frequently debug in platform-specific IDE (Visual Studio for Windows, Xcode for iOS, Android Studio for Android).

Setting up Visual Studio is dead simple. Download VS Community Edition (I'm using 2019), install `Game development with C++` workload, and select `C++ CMake tools for Windows` from `Individual components`. Once ready, clone this repo, use `Open a local folder`. VS will detect Cmake configuration and perform necessary steps (downloading dependencies and setting up a project) automatically.
