### ISSUE TITLE
No music under iOS

### ISSUE THREAD

**Issue by mutantant** [alexbatalov/fallout2-ce#234]
A similar issue to the one I just opened under the fallout1-ce repo, there is no music under iOS. Unlike fallout1-ce, I *do* get music in the MacOS version, but the iOS version has no music at all, while all other audio seems to be working fine.

Sideloaded via AltStore, iPadOS 15.7.1

**Comment by mutantant** [comment]
This was answered in the fallout1-ce repo, all has to do with various upper-case/lower-case filename issues and Unix vs DOS/Windows path conversions.

**Comment by QcSamuel** [comment]
could anyone provide a fixed fallout2 cfg ? for this
