### ISSUE TITLE
SIGSEGV in heap.cc (Fallout Nevada)

### ISSUE THREAD

**Issue by seadra** [alexbatalov/fallout2-ce#235]
Playing Fallout Nevada from an old save file. On the world map, city names aren't visible. When I click on a red buttons to go to a city, the game crashes. Running with gdb, the crash seems to be happening at

```
Thread 1 "fallout2-ce" received signal SIGSEGV, Segmentation fault.
0x00005555555d09f3 in fallout::heapBlockCompareBySize (a1=0x5555565affb0, a2=0x5555565affb8) at /home/user/src/fallout2-ce/src/heap.cc:1050
1050        return header1->size - header2->size;
```

<details>
<summary>Output:</summary>
<pre>
INFO: 
Fade time is 1224
Fade steps are 34
INFO: Chi squared is 30.872500, P = 4000.000000 at 0.05
INFO: Sequence is random, 95% confidence.
INFO: Initializing sound system...
[New Thread 0x7ffff3b826c0 (LWP 1779953)]
[New Thread 0x7fffee9836c0 (LWP 1779954)]
INFO: success.
INFO: Reading SNDLIST.LST Sound FX Count: 1362
INFO: Sounds are 
INFO: on.
INFO: Music is 
INFO: on.
INFO: Speech is 
INFO: on.
INFO: >gsound_init
INFO: >initMovie
INFO: >gmovie_init
INFO: >moviefx_init
INFO: >art_init
INFO: >tile_init
INFO: >obj_init
INFO: >cycle_init
INFO: >intface_init
INFO: >iso_init
INFO: >gmouse_init
INFO: >proto_init
INFO: >anim_init
INFO: >scr_init
INFO: >game_load_info
INFO: >scr_game_init
INFO: >wmWorldMap_init
INFO: >CharEditInit
INFO: >pip_init
INFO: >InitLoadSave
INFO: >gdialog_init
INFO: >combat_init
INFO: >automap_init
INFO: >message_init
INFO: >message_load
INFO: >scr_disable
INFO: >init_options_menu
INFO: >endgameDeathEndingInit
INFO: 
Playing movie: iplogo.mve
INFO: Direct 
INFO: Playing at (0, 0)  
INFO: not scaled
INFO: Movie aborted
INFO: Frames 9, dropped 0
INFO: 
Playing movie: intro.mve
INFO: Direct 
INFO: Playing at (0, 0)  
INFO: not scaled
INFO: Movie aborted
INFO: Frames 17, dropped 0
INFO: 
Playing movie: credits.mve
INFO: Direct 
INFO: Playing at (0, 0)  
INFO: not scaled
INFO: Movie aborted
INFO: Frames 44, dropped 0
INFO: Loading background sound file 07desert.acm...
INFO:  finding background sound 
INFO:  playing 
INFO: succeeded.
INFO: Loading sound file nmselec0.ACM...
INFO: succeeded.
INFO: Loading sound file nmselec1.ACM...
INFO: succeeded.
INFO:  Filename SAVEGAME\SLOT01\SAVE.DAT
INFO:  Filename SAVEGAME\SLOT08\SAVE.DAT
INFO: Loading sound file ib1p1xx1.ACM...
INFO: succeeded.
INFO:  Filename SAVEGAME\SLOT08\SAVE.DAT
INFO: 
LOADSAVE: Load name: 38
INFO: LOADSAVE: Load file header size read: 30051 bytes.
INFO: Resetting sound system...
INFO: done.
INFO: 
Scripts: [Game Reset]
INFO: LOADSAVE: Load function #0 data size read: 0 bytes.
INFO: LOADSAVE: Load function #1 data size read: 4 bytes.
INFO: LOADSAVE: Load function #2 data size read: 2784 bytes.
INFO: LOADSAVE: in SlotMap2Game
INFO: 
MAP: Loading SAVED map.
INFO: Loading background sound file wind2.acm...
INFO:  finding background sound 
INFO: in 2nd path 
INFO:  playing 
INFO: succeeded.
INFO: 
INFO: [Party Member 0]: None
INFO: Loading sound file rattle1.ACM...
INFO: succeeded.
INFO: 
Gsound: playing ambient map sfx: rattle1
INFO: LOADSAVE: Load function #3 data size read: 337 bytes.
INFO: LOADSAVE: Load function #4 data size read: 2784 bytes.
INFO: LOADSAVE: Load function #5 data size read: 4164 bytes.
INFO: LOADSAVE: Load function #6 data size read: 376 bytes.
INFO: LOADSAVE: Load function #7 data size read: 76 bytes.
INFO: LOADSAVE: Load function #8 data size read: 16 bytes.
INFO: LOADSAVE: Load function #9 data size read: 0 bytes.
INFO: LOADSAVE: Load function #10 data size read: 1428 bytes.
INFO: LOADSAVE: Load function #11 data size read: 4 bytes.
INFO: LOADSAVE: Load function #12 data size read: 180 bytes.
INFO: LOADSAVE: Load function #13 data size read: 20 bytes.
INFO: LOADSAVE: Load function #14 data size read: 0 bytes.
INFO: LOADSAVE: Load function #15 data size read: 8 bytes.
INFO: LOADSAVE: Load function #16 data size read: 4 bytes.
INFO: LOADSAVE: Load function #17 data size read: 80 bytes.
INFO: LOADSAVE: Load function #18 data size read: 5 bytes.
INFO: LOADSAVE: Load function #19 data size read: 7372 bytes.
INFO: LOADSAVE: Load function #20 data size read: 0 bytes.
INFO: LOADSAVE: Load function #21 data size read: 17 bytes.
INFO: LOADSAVE: Load function #22 data size read: 216 bytes.
INFO: 

[Party Members]:
INFO: 
Total Critter Count: 6

INFO: LOADSAVE: Load function #23 data size read: 32 bytes.
INFO: LOADSAVE: Load function #24 data size read: 96 bytes.
INFO: LOADSAVE: Load function #25 data size read: 16 bytes.
INFO: Loading background sound file 02Shaien.acm...
INFO:  finding background sound 
INFO:  playing 
INFO: succeeded.
INFO: LOADSAVE: Load function #26 data size read: 0 bytes.
INFO: LOADSAVE: Total load data read: 50070 bytes.
INFO: Loading sound file monitor.ACM...
INFO: succeeded.
INFO: 
 Saving ".SAV" map.
INFO: MODBRAH.SAV saved.
INFO: 
AUTOMAP: Saving AutoMap DB index 20, level 0
INFO: Loading background sound file 23world.acm...
INFO:  finding background sound 
INFO:  playing 
INFO: succeeded.
INFO: Heap Error: Bad guard end detected during unlock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: 
QUEUE PROCESS: Midnight!
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: 
QUEUE PROCESS: Midnight!
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: 
QUEUE PROCESS: Midnight!
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: 
QUEUE PROCESS: Midnight!
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Loading sound file ib1p1xx1.ACM...
INFO: succeeded.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Loading sound file ib1lu1x1.ACM...
INFO: succeeded.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: Heap Error: Bad guard end detected during lock.
INFO: 
[Heap]
Total free blocks: 1
Total free size: 4463764
Total moveable blocks: 257
Total moveable size: 2922140
Total locked blocks: 54
Total locked size: 1004656
Total system blocks: 0
Total system size: 0
Total handles: 320
Total heaps: 2
INFO: Heap Warning: Could not allocate block of 105104 bytes.
INFO: 
[Heap]
Total free blocks: 1
Total free size: 4463764
Total moveable blocks: 257
Total moveable size: 2922140
Total locked blocks: 54
Total locked size: 1004656
Total system blocks: 0
Total system size: 0
Total handles: 320
Total heaps: 2
INFO: Heap Warning: Could not allocate block of 105104 bytes.
INFO: 
[Heap]
Total free blocks: 1
Total free size: 4463764
Total moveable blocks: 257
Total moveable size: 2922140
Total locked blocks: 54
Total locked size: 1004656
Total system blocks: 0
Total system size: 0
Total handles: 320
Total heaps: 2
INFO: Heap Warning: Could not allocate block of 105104 bytes.
INFO: 
[Heap]
Total free blocks: 1
Total free size: 4463764
Total moveable blocks: 257
Total moveable size: 2922140
Total locked blocks: 54
Total locked size: 1004656
Total system blocks: 0
Total system size: 0
Total handles: 320
Total heaps: 2
INFO: Heap Warning: Could not allocate block of 105104 bytes.
INFO: 
[Heap]
Total free blocks: 1
Total free size: 4463764
Total moveable blocks: 257
Total moveable size: 2922140
Total locked blocks: 54
Total locked size: 1004656
Total system blocks: 0
Total system size: 0
Total handles: 320
Total heaps: 2
INFO: Heap Warning: Could not allocate block of 105104 bytes.
INFO: 
[Heap]
Total free blocks: 1
Total free size: 4463764
Total moveable blocks: 257
Total moveable size: 2922140
Total locked blocks: 54
Total locked size: 1004656
Total system blocks: 0
Total system size: 0
Total handles: 320
Total heaps: 2
INFO: Heap Warning: Could not allocate block of 105104 bytes.
INFO: 
[Heap]
Total free blocks: 1
Total free size: 4463764
Total moveable blocks: 257
Total moveable size: 2922140
Total locked blocks: 54
Total locked size: 1004656
Total system blocks: 0
Total system size: 0
Total handles: 320
Total heaps: 2
INFO: Heap Warning: Could not allocate block of 105104 bytes.
INFO: 
[Heap]
Total free blocks: 1
Total free size: 4463764
Total moveable blocks: 257
Total moveable size: 2922140
Total locked blocks: 54
Total locked size: 1004656
Total system blocks: 0
Total system size: 0
Total handles: 320
Total heaps: 2
INFO: Heap Warning: Could not allocate block of 105104 bytes.
INFO: 
[Heap]
Total free blocks: 1
Total free size: 4463764
Total moveable blocks: 257
Total moveable size: 2922140
Total locked blocks: 54
Total locked size: 1004656
Total system blocks: 0
Total system size: 0
Total handles: 320
Total heaps: 2
INFO: Heap Warning: Could not allocate block of 105104 bytes.
INFO: 
[Heap]
Total free blocks: 1
Total free size: 4463764
Total moveable blocks: 257
Total moveable size: 2922140
Total locked blocks: 54
Total locked size: 1004656
Total system blocks: 0
Total system size: 0
Total handles: 320
Total heaps: 2
INFO: Heap Warning: Could not allocate block of 105104 bytes.
INFO: Heap Error: Bad guard end detected during deallocate.
</pre>
</details>

Compiled from 81210f46af4177958e2c4932c33ddf86b3e96258

**Comment by alexbatalov** [comment]
- Post your save game.
- What is your Nevada version?

**Comment by seadra** [comment]
I did git bisect the bad commit is 2714dc1ea14b3786e28be3a631bae0dd43fe3b8f

- Will do
- Using the most recent version of Nevada Extended version

**Comment by seadra** [comment]
[SLOT08.zip](https://github.com/alexbatalov/fallout2-ce/files/10717524/SLOT08.zip)

The file README/Nevada_Extended_2032.txt starts with

```
Изменение игровых файлов в версии 2.0.3.2
```

(Can't read it but according to Google translate, it says "Changes in game files in version 2.0.3.2")

**Comment by APAmk2** [comment]
That is Fixed Edition repack by Foxx, he using SFall in repacks, just use original version from http://fallout-nevada.ucoz.ru/
And translate to eng from NMA.

**Comment by seadra** [comment]
@APAmk2 Are you saying that this crash does not get triggered in the version that you linked? Or you're saying that out of the context of this bug report?

Either way, there seems to be a bug in the current code base of fallout2-ce.

**Comment by APAmk2** [comment]
> @APAmk2 Are you saying that this crash does not get triggered in the version that you linked? Or you're saying that out of the context of this bug report?
> 
> Either way, there seems to be a bug in the current code base of fallout2-ce.

50/50, i haven't possibility to test original version, i said that only for future. Simple:please, don't use modified distributions of mods, especially versions with SFall.

**Comment by seadra** [comment]
Please let us know if you get around to testing it with the original version.

This is getting increasingly off-topic then, but in my case, I've never came across the site you linked, presumably because it's not in a language that I understand, and even if I knew what you just told me, I'd still take a version that comes in English out-of-the box from a web-page that I can read and understand.

If you are one of the developer of the Nevada and want people to use your version over alternatives, please consider making an English web-page and providing an English version of the game.

**Comment by alexbatalov** [comment]
Faulty `frm` is to blame - some have their `dataSize` field set to 0.

**Comment by Kokokokoka** [comment]
or a logged warning, perhaps
