### ISSUE TITLE
iOS could not find master datafile

### ISSUE THREAD

**Issue by Brandon1212b** [alexbatalov/fallout2-ce#236]
I have followed the instructions for iOS but when I go to play the game on my phone I get the following error:

"Could not find the master datafile. Please make sure the FALLOUT CD is in the drive and that you are running fallout from the directory you installed to"

**Comment by alexbatalov** [comment]
Did you copy game assets from Windows/Mac installation?

> Use Finder (macOS Catalina and later) or iTunes (Windows and macOS Mojave or earlier) to copy `master.dat`, `critter.dat`, `patch000.dat`, and `data` folder to "Fallout 2" app ([how-to](https://support.apple.com/HT210598)).

**Comment by Brandon1212b** [comment]
The problem is because the files are case sensitive and copy and pasting from the steam file folder would bring over all caps files. I was able to fix it by renaming the file names. I recommend putting this is the installation instructions
