### ISSUE TITLE
[Question] does this support HQ audio files

### ISSUE THREAD

**Issue by QcSamuel** [alexbatalov/fallout2-ce#239]
like this HQ audio files on github https://github.com/BGforgeNet/Fallout2-HQ-music

**Comment by APAmk2** [comment]
Tryed HQ audio for Sonora and that doesnt works (sound plays, but with very lounded tone), looks like HQ support not implemented yet.

**Comment by alexbatalov** [comment]
HQ sounds are not yet supported. 44.1 kHz `acm` is probably easy to implement. Other formats will need significant changes to audio engine and `SDL_mixer` as dependency.

**Comment by APAmk2** [comment]
@QcSamuel Can you close issue if answer is suits, please?
