### ISSUE TITLE
Failure initializing input devices

### ISSUE THREAD

**Issue by DoS347** [alexbatalov/fallout2-ce#244]
Hello! I get this error over and over again "Failure initializing input devices". And it affects both Fallout 1 and Fallout 2. As I understood, the error is related to the fact that the game does not see the physical keyboard and mouse. What actions I've tried:

1. I edited the file ddraw.ini, line BackroundKeyboard and BackgroundMouse for Fallout 2 and file f1_res.ini for the first part of the game, line ALT_MOUSE_INPUT
2. I tried putting different versions and builds of the game

What other steps can I take to fix this error on my tablet? Maybe the problem is related to Android 6, because everything works on a more recent device. Maybe I have the wrong config ddraw.ini or f1_res? In that case I would like to ask for an example of the correct config.

**Comment by alexbatalov** [comment]
Your Android version is too old and does not support relative mouse mode used by the game. I'm looking for a way to get rid of this requirement which will fix your problem, but I don't have ETA at this time.

**Comment by DoS347** [comment]
Thanks for the reply! Can you please tell me what is the minimum android version I need to be able to buy such a device?
