### ISSUE TITLE
0 (zero) key behavior in dialogue

### ISSUE THREAD

**Issue by qiwichupa** [alexbatalov/fallout2-ce#247]
The 0 key in dialogs should end the dialogue (tested in the gog version). The fallout2-ce ignores pressing

**Comment by alexbatalov** [comment]
This behaviour is actually result of a bug that abnormally terminates game dialogue (selecting non-existent option). Right now you can opt out of this fix via `DialogueFix` in `ddraw.ini`, but I plan to remove this setting entirely in future versions.
