### ISSUE TITLE
Sonora is completely playable

### ISSUE THREAD

**Issue by APAmk2** [alexbatalov/fallout2-ce#249]
Hi, i ended my Sonora playthrough yesterday for 100%, all quests and endings closed. I think that is something like usable information. Please close issue when you read this.

**Comment by WastelandMyx** [comment]
Hi, which on which OS You were playing sonora? I was trying to open it (version 1.10c, I am not sure but I think it does not have sfall) on iPad but with No success…

**Comment by APAmk2** [comment]
Hi, you need original version from devs site, here the link http://fallout-nevada.ucoz.ru/index/opisanie_fallout_sonora/0-59 , you need to unpack data folder, master.dat, critter.dat and fallout2.cfg, i hope it will help you.

**Comment by roginvs** [comment]
@APAmk2 Did you make any additional configuration or it just works out-of-the-box? For example Nevada needs few additional options (https://github.com/roginvs/fallout2-ce/tree/main/os/web#fallout-nevada-notes) like starting date and setting `MovieTimer_artimer4` to very high unrealistic value to prevent vault city from disappearing.

**Comment by APAmk2** [comment]
Nope, i used original 1.10 version from Nevada Band site and that works fine without any additional configs
