### ISSUE TITLE
Hey

### ISSUE THREAD

**Issue by alexbatalov** [alexbatalov/fallout2-ce#257]
It's been a while, huh? As you see my account has finally been reinstated. There was an issue with one of the email addresses. Apparently my initial support ticket was incorrectly triaged and, let me cite this, "was routed to the wrong inbox". Once I was approached by the support team member, it took one additional message and about an hour to resolve.

There was no progress on Fallouts behind the scenes. The development is going to be continued right where it was suddenly interrupted. Thanks for your patience.

**Comment by APAmk2** [comment]
Welcome back! 🎉

**Comment by Exarkuniv** [comment]
Welcome back. 
i was so worried that project was over, glad thats not the case 🎉

**Comment by QuantumApprentice** [comment]
<3

**Comment by SCARaw** [comment]
Good to have you back
please work on the gameplay xD
keys 1-8 on the side of the screen that correspon with Fallout 2 Actions would be great
Touch screen support with touch screen mode toggle too xD
also right click switcher
and item highlight button 
11 buttons on the sides of the screens
Similar to openMW custom keys or f2.exe

i don't really understand premisse of this project as original F2 with mods seems to be closer to my perfect fallout
but i still hope to see it evolves

**Comment by JordanCpp** [comment]
I am very happy. The project is excellent. I'm glad that everything has returned to normal.
