### ISSUE TITLE
Troubles with running the app on android in full screen - solved, Resolution must be scalled ti height 480p

### ISSUE THREAD

**Issue by SCARaw** [alexbatalov/fallout2-ce#265]
whenever i use it
it run tiny window
no matter how hard i edit inis inside it runs very small window

any help wiith setting it up on android?

**Comment by SCARaw** [comment]
This are my CFG file and INI file
https://cdn.discordapp.com/attachments/643141701975801873/1096428032954204220/fallout_2_ce_bad.zip
idk how to send them
[fallout 2 ce bad.zip](https://github.com/alexbatalov/fallout2-ce/files/11233323/fallout.2.ce.bad.zip)

**Comment by SCARaw** [comment]
https://cdn.discordapp.com/attachments/643141701975801873/1096428381362454608/Screenshot_20230414-153306_Fallout_2.jpg
https://cdn.discordapp.com/attachments/643141701975801873/1096428381689614439/Screenshot_20230414-153318_Fallout_2.jpg

**Comment by SCARaw** [comment]
this is how it looks on phone
on Giant TV size screen you might look at think and say its decent
but on phone its a nightmare

i reinstalled this app and re-edited files so many times
i have no clue what to change to improve this situation
entire things just does not wanna streech to full screen

**Comment by SCARaw** [comment]
Please help, i just wanted to play some fallout on mobile just like i can play morrowind/stardew valley

**Comment by alexbatalov** [comment]
Your resolution is extremely big (1920x1080). See readme how to properly configure for mobile phone.
