### ISSUE TITLE
22 KhZ (Original) Voices are bugged

### ISSUE THREAD

**Issue by APAmk2** [alexbatalov/fallout2-ce#268]
Using latest build from Actions, HQ music (not necessary, you'll meet that with original music too) and original (CD) US Fallout 2 with all patches, at russificator by "1С" i meet same thing.

https://user-images.githubusercontent.com/107351397/233846025-0201e49c-bff7-41a2-a06f-7547a04a7397.mp4

**Comment by alexbatalov** [comment]
Looks like original speech acms have incorrect number of channels specified in file headers (2, should be 1).
