### ISSUE TITLE
Loading saves are broken by #214

### ISSUE THREAD

**Issue by seadra** [alexbatalov/fallout2-ce#273]
The commit aa99b2e broke the load functionality. Trying to load any old save now results in the error (on Linux)

> Error loading game
> Unable to load game

**Comment by alexbatalov** [comment]
I bet #214 and #272 fixed loading of `patch000.dat` on case-sensitive file systems. Patched and non-patched game have different number of global variables so save games are incompatible. Try to remove `patch000.dat` from the game directory to see if it works.

**Comment by seadra** [comment]
I tried removing patch000.dat and patch001.dat file from the game directory, but unfortunately it didn't work

**Comment by alexbatalov** [comment]
Post your savegame

**Comment by seadra** [comment]
I'm actually trying to load the save file from [an earlier post of mine](https://github.com/alexbatalov/fallout2-ce/issues/235#issuecomment-1427154270)

**Comment by alexbatalov** [comment]
This particular save is from Nevada, runs fine on both Android and iOS. Will check on Linux next week.

**Comment by seadra** [comment]
Is there anything that I can do to debug this issue on my end? (I just compiled with [ec72247](https://github.com/alexbatalov/fallout2-ce/commit/ec722475b6a9f9c3a440b275e5d5d129b48746f7) and still fails to load)

**Comment by roginvs** [comment]
I can confirm that it works on latest commit (i.e. ec722475b6a9f9c3a440b275e5d5d129b48746f7) on Linux but I had to rename `Patch000.dat -> patch000.dat` and `Patch001.dat -> patch001.dat` files. Game is Nevada Eng v2.0.3.3 from https://www.nma-fallout.com/threads/fallout-nevada-extended.207311/

PS: It also works fine on webassembly build https://fallout-nevada.ru/ . Here is your savegame but re-packed as `.tar.gz`, you can upload it into webpage and check that it works [SLOT08.tar.gz](https://github.com/alexbatalov/fallout2-ce/files/11601819/SLOT08.tar.gz)

**Comment by alexbatalov** [comment]
I've checked your save game on v2.0.3.3 downloaded from the NMA thread, it does work. To justify things, here is what I did:

Extract everything from installer:
```console
$ innoextract \[con\]\ F2\ Nevada\ Mod\ \(Extended\)\ HD\ \[v2.0.3.3\].exe -d nevada-installer-2.0.3.3
```

Copy necessary files into new folder:
```console
$ mkdir nevada
$ cd nevada
$ cp -r ../nevada-installer-2.0.3.3/app/DATA ./
$ cp ../nevada-installer-2.0.3.3/app/Patch000.dat ./
$ cp ../nevada-installer-2.0.3.3/app/Patch001.dat ./
$ cp ../fallout2/master.dat ./
$ cp ../fallout2/critter.dat ./
$ cp -r ../SLOT08 ./DATA/SAVEGAME/
```

Please follow these steps and post your results.

Your save game does not work on more modern 2.4.1 and probably won't work on other versions as there are differences in party members (each needs it's own proto file otherwise loading is impossible).

**Comment by seadra** [comment]
[My folder structure](https://www.mediafire.com/file/fm6sbcuknc2sg7i/nevada.zip/file)

**Comment by seadra** [comment]
I can confirm that the save file is working currently at 37e4822
Thanks a bunch!

**Comment by seadra** [comment]
The problem is `compat_access` function. Modifying the `compact_access` in `src/platform_compat.cc` as

```c
int compat_access(const char* path, int mode)
{
    return access(path, mode);
}
```

works as a workaround
