### ISSUE TITLE
Crash with Sonora gameplay

### ISSUE THREAD

**Issue by Nordsoft91** [alexbatalov/fallout2-ce#281]
1. Install data from Fallout Sonora (I took original version here http://fallout-nevada.ucoz.ru/index/opisanie_fallout_sonora/0-59)
2. Install f2ce-1.2
3. Start game with any character
4. Go inside building, speak with grandma
5. Observe crash

**Works well in 1.1 and 1.0.2, problem observed only with 1.2**

OS: MacOS Catalina

**Comment by APAmk2** [comment]
That already fixed, i've found that bug and Alex Fixed it, release is too outdated, use debug from Github actions, please.

**Comment by Nordsoft91** [comment]
Can confirm completion of Fallout of Sonora on MacOS. Built locally from that revision efdc2e019982a863aa477bc6f0285c20dfe49348
