### ISSUE TITLE
Enabling debugPrint with DEBUGACTIVE

### ISSUE THREAD

**Issue by seadra** [alexbatalov/fallout2-ce#298]
There seems to be a functionality to turn on debug logging using the environment variable `DEBUGACTIVE`, which can be set to `mono`, `log`, `screen`, `gnw` according to debug.cc. This is activated by the function `_debug_register_env()` but it is never called. Should it be called somewhere during initialization?

**Comment by phobos2077** [comment]
This issue is tackled in sfall Debug mode, so I suggest just repeating the same. "mono" and "screen" doesn't do anything, so they are useless. Which leaves only log and gns (debug window). Sfall allows to choose one or both with INI setting.

Also I recommended to take a look at recent Console Window feature in sfall (WinAPI console). It's very useful for debugging along with the debug log.

**Comment by seadra** [comment]
> "mono" and "screen" doesn't do anything, so they are useless.

I disagree, `screen` prints the debug information to stdout, which I found to be pretty useful.

**Comment by phobos2077** [comment]
> I disagree, `screen` prints the debug information to stdout, which I found to be pretty useful.

Didn't know about it. I tried running this with original game (via sfall patch) and it didn't print anything to the console where I ran it. So I assumed it didn't work, I guess this is not the case with CE.

I think there should be a flags option to toggle each possible output for logs.

**Comment by alexbatalov** [comment]
I've borrowed debug mode handling from `mapper2.exe`.

Debug modes:
- `environment`: grab mode from `DEBUGACTIVE` env variable, this is the default.
- `screen`: prints to console
- `log`: prints to `debug.log` file
- `mono`: I guess this one is for DOS, should print directly to screen buffer via raw VGA memory (doesn't work and I'm not sure if the implementation is correct)
- `gnw`: print to in-game window (works but buggy)

**Comment by alexbatalov** [comment]
Yes, `screen` works. On Windows you need to pipe output somewhere, eg. `fallout2-ce.exe > out.txt`. I'm not sure if you can pipe it directly to screen to achieve Linux terminal behaviour. There is `tee` in powershell, but I was not able to get messages appear on the screen (flushed on exit).

**Comment by phobos2077** [comment]
In recent sfall, we have a separate feature for printing logs (engine, script, or sfall logs with filtering) to a console window created by WinAPI. Would be nice to have something like this in future, and/or expand "gnw" option.
