### ISSUE TITLE
Будет ли порт Fallout 3 

### ISSUE THREAD

**Issue by SERAPHIMVDK** [alexbatalov/fallout2-ce#301]

**Comment by SERAPHIMVDK** [comment]
https://archive.org/details/gamebryo-sdks вроде как исходный код движка накотором был создан fallout 3 и new vegas

**Comment by APAmk2** [comment]
Когда захотят - будут делать, здесь сейчас заняты лишь движком Fallout и Fallout 2, закройте пожалуйста Issue и не задавайте таких глупых вопросов впредь

**Comment by alexbatalov** [comment]
@SERAPHIMVDK Fallout 3 is too big to reverse engineer solo. Even with GameBryo source code available (let alone licensing stuff) it is 10+ years of work.
