### ISSUE TITLE
Build instructions missing in README

### ISSUE THREAD

**Issue by spamegg1** [alexbatalov/fallout2-ce#312]
It says "Download the latest release or build from source."

I had to look into `.github/workflows/ci-build.yaml` to figure it out. Install missing dependencies, then the right configure command, then the right `cmake` command to build.

Maybe that could be made clearer? Or provide a more familiar `./configure` + `make` procedure?

**Comment by eirnym** [comment]
the common flow for cmake-based projects is following (`build` folder is an example, change it to your own wish) :

```
$ mkdir build
$ cd build
$ cmake ../
$ make
$ # copy files required to whatever you want
```
