### ISSUE TITLE
Unable to build on Ubuntu 20.04

### ISSUE THREAD

**Issue by alexbatalov** [alexbatalov/fallout2-ce#32]
See #25

**Comment by k3tamina** [comment]
Could you post compiler output?

**Comment by burner1024** [comment]
it builds, just crashes on launch

**Comment by alexbatalov** [comment]
I've done some research on fresh minimal Ubuntu 20.04. You'll need:

```console
$ sudo dpkg --add-architecture i386
$ sudo apt install zlib1g:i386 libsdl2-2.0-0:i386 libstdc++6:i386
```

Check there are no errors:
```console
$ ldd fallout2-ce
```

On my VM it starts just fine. But I've had segfault trying to speak with Klint. Next time it was fine, dialog started as expected. So I guess there is mess in the memory somewhere.

**Comment by burner1024** [comment]
No problem with ldd.
Actually, the previous time I launched on RPU, that's what's crashed. When trying on UPU, it launches.

**Comment by burner1024** [comment]
Anyway, for the time being, probably better to build with debug symbols, I doubt there's going any noticeable speed difference, but debug would be easier.

**Comment by Risu** [comment]
On my 20.04 based 64-bit distro I've built with forced
```
add_subdirectory("third_party/zlib")
add_subdirectory("third_party/sdl2")
```
in "CMakeLists.txt" file and with cmake executed with DCMAKE_TOOLCHAIN_FILE parameter.
Additional installed libraries:
```
libxcursor-dev:i386
libxinerama-dev:i386
libxrandr-dev:i386
libxxf86vm-dev:i386
libxss-dev:i386
libxi-dev:i386
libdbus-1-dev:i386
and libwayland-bin
```
Quick look:
Movies have minor artifacts (black squares on some colours) and game crashing like in comment above when speaking with Klint (looks like distance related).

**Comment by JanSimek** [comment]
I do not know how to decompile and check the original code but here is the problem. Perhaps, the rotation parameter should be % ROTATION_COUNT?

```diff
diff --git a/src/animation.cc b/src/animation.cc
index 6d6209a..e694c58 100644
--- a/src/animation.cc
+++ b/src/animation.cc
@@ -1892,7 +1892,7 @@ int animateMoveObjectToObject(Object* from, Object* to, int a3, int anim, int an
     }
 
     if (v13) {
-        ptr->field_24 = tileGetTileInDirection(to->tile, ptr->field_24 + v13 + ptr->field_1C + 3, 1);
+        ptr->field_24 = tileGetTileInDirection(to->tile, (ptr->field_24 + v13 + ptr->field_1C + 3) % ROTATION_COUNT, 1);
     }
 
     if (v13 == 2) {
```
