### ISSUE TITLE
Nevada: game crash when climb the building

### ISSUE THREAD

**Issue by sonilyan** [alexbatalov/fallout2-ce#328]
[SLOT05.zip](https://github.com/alexbatalov/fallout2-ce/files/12914388/SLOT05.zip)

click on the door of the building, then choose to climb up, and the game crashes

**Comment by roginvs** [comment]
What Nevada version do you use?

**Comment by sonilyan** [comment]
> What Nevada version do you use?

F2 Nevada Mod (Extended) HD [v2.0.3.3]

**Comment by sonilyan** [comment]
[SLOT07.zip](https://github.com/alexbatalov/fallout2-ce/files/12923165/SLOT07.zip)
Sonora : use repair to the power generationer when game crash.

It should be the same bug as Nevada
![1](https://github.com/alexbatalov/fallout2-ce/assets/26177176/1bf26538-e78f-4eef-975b-e160da296729)

**Comment by roginvs** [comment]
I tried to reproduce your issue using your savegame, but I successfully climbed to the roof (using door).

I was using Linux platform with this patch https://github.com/alexbatalov/fallout2-ce/pull/325 but probably this is not relevant to your issue because you are running Windows

**Comment by sonilyan** [comment]
> I tried to reproduce your issue using your savegame, but I successfully climbed to the roof (using door).
> 
> I was using Linux platform with this patch #325 but probably this is not relevant to your issue because you are running Windows


I used version 1.2 released by Alex, and this BUG did not appear, but the exe I compiled using the latest main branch had this problem, and this bug can also appear on Android phones.

**Comment by sonilyan** [comment]
It seems that the variable was not initialized correctly. I added the initialization of the variable in the scriptRead function for testing, and there was no more crash.
