### ISSUE TITLE
Character file saves wont load up on the character creator

### ISSUE THREAD

**Issue by ninonook1** [alexbatalov/fallout2-ce#352]
on the character creator when i try to load up a character that i saved, it doesnt seem to detect if theyre are any saved files. either that or its looking at the wrong place, im not sure what the technical issue is, its just showing a black as if the files arnt there (i use a macbook air 2015)

**Comment by alexbatalov** [comment]
Thanks for reporting, it's fixed.

**Comment by ninonook1** [comment]
alright so its aware of the file, as when i attempt to save a file with the same name, it will show a prompt to overwrite the character save data, however when i attempt to load a character it will still show nothing, ive tried clicking around on the selection of the load character to see if maybe the selections are still there and its just invisible. but so far nothing, it could be a glitch on my end, but im not sure.
