### ISSUE TITLE
iOS on iPhone vs iPad

### ISSUE THREAD

**Issue by LowRiven** [alexbatalov/fallout2-ce#354]
Issue Description:

The Fallout 2 iOS port works fine on iPhone devices but encounters display issues on iPad devices. The game does not fill the entire screen, similar to the behavior seen in mobile ports like Wolt, where there is a resize button that makes the application smaller or occupies only a portion of the screen.

Comparison with Fallout 1:
Upon comparing settings and files, it was observed that Fallout 1 functions correctly on iPads without encountering the display above issues. One notable difference discovered is the absence of the UIDeviceFamily key in the info.plist file of Fallout 2 .ipa file. In Fallout 1, however, this key is present, I probably have bad formatting so I don't see values there but just squares.

Thank you so much for this awesome project!

![fallout1](https://github.com/alexbatalov/fallout2-ce/assets/149584673/a11b45d7-4f52-4583-b16d-06aa45fb070d)
![fallout2](https://github.com/alexbatalov/fallout2-ce/assets/149584673/d5108c8a-eb34-49a4-900f-fd17c2743cc9)

**Comment by alexbatalov** [comment]
Check out v1.3, it uses the same approach for iOS building as in F1.

**Comment by LowRiven** [comment]
@alexbatalov You are the best! Thank you so much!
