### ISSUE TITLE
Any chance for a newer build?

### ISSUE THREAD

**Issue by eisnerguy1** [alexbatalov/fallout2-ce#358]
I was wondering if there'd be any chance for an updated/newer build?  I'm mainly looking for a build with [this 2x scaling fix](https://github.com/alexbatalov/fallout2-ce/pull/306). The builds in the Actions section have expired unfortunately. If a newer build can't be uploaded, could you include the build steps in the ReadMe? 

Thanks!

**Comment by orffen** [comment]
Was just about to ask for this, since there was a recent fallout1-ce build.

**Comment by alexbatalov** [comment]
Hey guys, sure will do, need to fix a couple of things. Apple has finally decomissioned old notarization utility which broke release workflow on macOS.

**Comment by alexbatalov** [comment]
Published v1.3. Enjoy!

**Comment by eisnerguy1** [comment]
Thanks so much, I really appreciate it 👍🏻
