### ISSUE TITLE
unable to save game (1.3)

### ISSUE THREAD

**Issue by psemiletov** [alexbatalov/fallout2-ce#362]
Hello! 
Archlinux, GOG, "unable to save game". Old savings are loading well.
Just for the test, I removed "SAVES" directory to try a fresh start. But no chance,  "unable to save game".

**Comment by alexbatalov** [comment]
Damn, I guess paths issue is still there. Post your directory structure and `fallout2.cfg` to see if I can reproduce it.

**Comment by psemiletov** [comment]
fallout2.cfg:

[debug]
mode=environment
output_map_data_info=0
show_load_info=0
show_script_messages=0
show_tile_num=0

[mapper]
default_f8_as_game=1
fix_map_inventory=0
fix_map_objects=0
ignore_rebuild_errors=0
librarian=0
override_librarian=0
rebuild_protos=0
run_mapper_as_game=0
save_text_maps=0
show_pid_numbers=0
sort_script_list=0
use_art_not_protos=0

[preferences]
brightness=1.000000
combat_difficulty=1
combat_looks=0
combat_messages=1
combat_speed=50
combat_taunts=1
game_difficulty=1
item_highlight=1
language_filter=0
mouse_sensitivity=1.000000
player_speed=1
player_speedup=0
running=0
running_burning_guy=1
subtitles=0
target_highlight=2
text_base_delay=6.000000
text_line_delay=2.000000
violence_level=3

[sound]
cache_size=448
debug=0
debug_sfxc=1
device=-1
dma=-1
initialize=1
irq=-1
master_volume=19899
music=1
music_path1=sound/music/
music_path2=sound/music/
music_volume=22281
port=-1
sndfx_volume=22281
sounds=1
speech=1
speech_volume=22281

[system]
art_cache_size=8
color_cycling=1
critter_dat=critter.dat
critter_patches=data
cycle_speed_factor=1
executable=game
free_space=20480
hashing=1
interrupt_walk=1
language=english
master_dat=master.dat
master_patches=data
scroll_lock=0
splash=4
times_run=5

**Comment by psemiletov** [comment]
.

├── critter.dat
├── data
│   ├── art
│   │   └── tiles
│   │       └── grid000.FRM
│   ├── critter.dat
│   ├── data
│   │   ├── data
│   │   └── f2_res.dat
│   ├── maps
│   │   ├── ARBRIDGE.SAV
│   │   ├── ARCAVES.SAV
│   │   ├── ARGARDEN.SAV
│   │   ├── ARTEMPLE.SAV
│   │   ├── ARVILLAG.SAV
│   │   ├── BROKEN1.SAV
│   │   ├── DENBUS1.SAV
│   │   ├── DENBUS2.SAV
│   │   ├── GECKSETL.SAV
│   │   ├── KLACANYN.SAV
│   │   ├── KLADWTWN.SAV
│   │   ├── KLAGRAZ.SAV
│   │   ├── KLAMALL.SAV
│   │   ├── KLATOXCV.SAV
│   │   ├── MBCLOSE.SAV
│   │   ├── MODGARD.SAV
│   │   ├── MODINN.SAV
│   │   ├── MODMAIN.SAV
│   │   ├── MODSHIT.SAV
│   │   ├── MODWELL.SAV
│   │   ├── NAVARRO.SAV
│   │   ├── NCR1.SAV
│   │   ├── NCR2.SAV
│   │   ├── NCRENT.SAV
│   │   ├── NEWR1.SAV
│   │   ├── NEWR2.SAV
│   │   ├── NEWR3.SAV
│   │   ├── RAIDERS1.SAV
│   │   ├── REDDOWN.SAV
│   │   ├── REDDTUN.SAV
│   │   ├── REDMENT.SAV
│   │   ├── REDMTUN.SAV
│   │   ├── REDWAME.SAV
│   │   ├── REDWAN1.SAV
│   │   ├── RNDBRIDG.SAV
│   │   ├── SFCHINA2.SAV
│   │   ├── SFCHINA.SAV
│   │   ├── V15ENT.SAV
│   │   ├── V15SENT.SAV
│   │   ├── VAULT15.SAV
│   │   └── VCTYCTYD.SAV
│   ├── MAPS
│   ├── proto
│   │   ├── critters
│   │   └── items
│   ├── SAVEGAME
│   │   ├── SLOT01
│   │   │   ├── ARBRIDGE.SAV
│   │   │   ├── ARCAVES.SAV
│   │   │   ├── ARGARDEN.SAV
│   │   │   ├── ARTEMPLE.SAV
│   │   │   ├── ARVILLAG.SAV
│   │   │   ├── AUTOMAP.SAV
│   │   │   ├── BROKEN1.SAV
│   │   │   ├── DENBUS1.SAV
│   │   │   ├── DENBUS2.SAV
│   │   │   ├── GECKSETL.SAV
│   │   │   ├── KLACANYN.SAV
│   │   │   ├── KLADWTWN.SAV
│   │   │   ├── KLAGRAZ.SAV
│   │   │   ├── KLAMALL.SAV
│   │   │   ├── KLATOXCV.SAV
│   │   │   ├── MBCLOSE.SAV
│   │   │   ├── MODGARD.SAV
│   │   │   ├── MODINN.SAV
│   │   │   ├── MODMAIN.SAV
│   │   │   ├── MODSHIT.SAV
│   │   │   ├── MODWELL.SAV
│   │   │   ├── NAVARRO.SAV
│   │   │   ├── NCR1.SAV
│   │   │   ├── NCR2.SAV
│   │   │   ├── NCRENT.SAV
│   │   │   ├── NEWR1.SAV
│   │   │   ├── NEWR2.SAV
│   │   │   ├── NEWR3.SAV
│   │   │   ├── proto
│   │   │   │   ├── critters
│   │   │   │   │   ├── 00000062.pro
│   │   │   │   │   ├── 00000079.pro
│   │   │   │   │   ├── 00000089.pro
│   │   │   │   │   ├── 00000097.pro
│   │   │   │   │   ├── 00000107.pro
│   │   │   │   │   ├── 00000136.pro
│   │   │   │   │   ├── 00000152.pro
│   │   │   │   │   ├── 00000160.pro
│   │   │   │   │   ├── 00000161.pro
│   │   │   │   │   ├── 00000162.pro
│   │   │   │   │   ├── 00000163.pro
│   │   │   │   │   ├── 00000164.pro
│   │   │   │   │   ├── 00000165.pro
│   │   │   │   │   ├── 00000191.pro
│   │   │   │   │   ├── 00000195.pro
│   │   │   │   │   ├── 00000196.pro
│   │   │   │   │   ├── 00000197.pro
│   │   │   │   │   ├── 00000265.pro
│   │   │   │   │   ├── 00000342.pro
│   │   │   │   │   ├── 00000379.pro
│   │   │   │   │   ├── 00000380.pro
│   │   │   │   │   ├── 00000381.pro
│   │   │   │   │   ├── 00000384.pro
│   │   │   │   │   └── 00000471.pro
│   │   │   │   └── items
│   │   │   │       └── 00000455.pro
│   │   │   ├── RAIDERS1.SAV
│   │   │   ├── REDDOWN.SAV
│   │   │   ├── REDDTUN.SAV
│   │   │   ├── REDMENT.SAV
│   │   │   ├── REDMTUN.SAV
│   │   │   ├── REDWAME.SAV
│   │   │   ├── REDWAN1.SAV
│   │   │   ├── RNDBRIDG.SAV
│   │   │   ├── SAVE.DAT
│   │   │   ├── SFCHINA2.SAV
│   │   │   ├── SFCHINA.SAV
│   │   │   ├── V15ENT.SAV
│   │   │   ├── V15SENT.SAV
│   │   │   ├── VAULT15.SAV
│   │   │   └── VCTYCTYD.SAV
│   │   ├── SLOT02
│   │   │   ├── ARBRIDGE.SAV
│   │   │   ├── ARCAVES.SAV
│   │   │   ├── ARGARDEN.SAV
│   │   │   ├── ARTEMPLE.SAV
│   │   │   ├── ARVILLAG.SAV
│   │   │   ├── AUTOMAP.SAV
│   │   │   ├── BROKEN1.SAV
│   │   │   ├── DENBUS1.SAV
│   │   │   ├── DENBUS2.SAV
│   │   │   ├── GECKSETL.SAV
│   │   │   ├── KLACANYN.SAV
│   │   │   ├── KLADWTWN.SAV
│   │   │   ├── KLAGRAZ.SAV
│   │   │   ├── KLAMALL.SAV
│   │   │   ├── KLATOXCV.SAV
│   │   │   ├── MBCLOSE.SAV
│   │   │   ├── MODGARD.SAV
│   │   │   ├── MODINN.SAV
│   │   │   ├── MODMAIN.SAV
│   │   │   ├── MODSHIT.SAV
│   │   │   ├── MODWELL.SAV
│   │   │   ├── NAVARRO.SAV
│   │   │   ├── NCR1.SAV
│   │   │   ├── NCR2.SAV
│   │   │   ├── NCRENT.SAV
│   │   │   ├── NEWR1.SAV
│   │   │   ├── NEWR2.SAV
│   │   │   ├── NEWR3.SAV
│   │   │   ├── proto
│   │   │   │   ├── critters
│   │   │   │   │   ├── 00000062.pro
│   │   │   │   │   ├── 00000079.pro
│   │   │   │   │   ├── 00000089.pro
│   │   │   │   │   ├── 00000097.pro
│   │   │   │   │   ├── 00000107.pro
│   │   │   │   │   ├── 00000136.pro
│   │   │   │   │   ├── 00000152.pro
│   │   │   │   │   ├── 00000160.pro
│   │   │   │   │   ├── 00000161.pro
│   │   │   │   │   ├── 00000162.pro
│   │   │   │   │   ├── 00000163.pro
│   │   │   │   │   ├── 00000164.pro
│   │   │   │   │   ├── 00000165.pro
│   │   │   │   │   ├── 00000191.pro
│   │   │   │   │   ├── 00000195.pro
│   │   │   │   │   ├── 00000196.pro
│   │   │   │   │   ├── 00000197.pro
│   │   │   │   │   ├── 00000265.pro
│   │   │   │   │   ├── 00000342.pro
│   │   │   │   │   ├── 00000379.pro
│   │   │   │   │   ├── 00000380.pro
│   │   │   │   │   ├── 00000381.pro
│   │   │   │   │   ├── 00000384.pro
│   │   │   │   │   └── 00000471.pro
│   │   │   │   └── items
│   │   │   │       └── 00000455.pro
│   │   │   ├── RAIDERS1.SAV
│   │   │   ├── REDDOWN.SAV
│   │   │   ├── REDDTUN.SAV
│   │   │   ├── REDMENT.SAV
│   │   │   ├── REDMTUN.SAV
│   │   │   ├── REDWAME.SAV
│   │   │   ├── REDWAN1.SAV
│   │   │   ├── RNDBRIDG.SAV
│   │   │   ├── SAVE.DAT
│   │   │   ├── SFCHINA2.SAV
│   │   │   ├── SFCHINA.SAV
│   │   │   ├── V15ENT.SAV
│   │   │   ├── V15SENT.SAV
│   │   │   ├── VAULT15.SAV
│   │   │   └── VCTYCTYD.SAV
│   │   ├── SLOT03
│   │   │   ├── ARBRIDGE.SAV
│   │   │   ├── ARCAVES.SAV
│   │   │   ├── ARGARDEN.SAV
│   │   │   ├── ARTEMPLE.SAV
│   │   │   ├── ARVILLAG.SAV
│   │   │   ├── AUTOMAP.SAV
│   │   │   ├── BROKEN1.SAV
│   │   │   ├── DENBUS1.SAV
│   │   │   ├── DENBUS2.SAV
│   │   │   ├── GECKSETL.SAV
│   │   │   ├── KLACANYN.SAV
│   │   │   ├── KLADWTWN.SAV
│   │   │   ├── KLAGRAZ.SAV
│   │   │   ├── KLAMALL.SAV
│   │   │   ├── KLATOXCV.SAV
│   │   │   ├── MBCLOSE.SAV
│   │   │   ├── MODGARD.SAV
│   │   │   ├── MODINN.SAV
│   │   │   ├── MODMAIN.SAV
│   │   │   ├── MODSHIT.SAV
│   │   │   ├── MODWELL.SAV
│   │   │   ├── NAVARRO.SAV
│   │   │   ├── NCR1.SAV
│   │   │   ├── NCR2.SAV
│   │   │   ├── NCRENT.SAV
│   │   │   ├── NEWR1.SAV
│   │   │   ├── NEWR2.SAV
│   │   │   ├── NEWR3.SAV
│   │   │   ├── proto
│   │   │   │   ├── critters
│   │   │   │   │   ├── 00000062.pro
│   │   │   │   │   ├── 00000079.pro
│   │   │   │   │   ├── 00000089.pro
│   │   │   │   │   ├── 00000097.pro
│   │   │   │   │   ├── 00000107.pro
│   │   │   │   │   ├── 00000136.pro
│   │   │   │   │   ├── 00000152.pro
│   │   │   │   │   ├── 00000160.pro
│   │   │   │   │   ├── 00000161.pro
│   │   │   │   │   ├── 00000162.pro
│   │   │   │   │   ├── 00000163.pro
│   │   │   │   │   ├── 00000164.pro
│   │   │   │   │   ├── 00000165.pro
│   │   │   │   │   ├── 00000191.pro
│   │   │   │   │   ├── 00000195.pro
│   │   │   │   │   ├── 00000196.pro
│   │   │   │   │   ├── 00000197.pro
│   │   │   │   │   ├── 00000265.pro
│   │   │   │   │   ├── 00000342.pro
│   │   │   │   │   ├── 00000379.pro
│   │   │   │   │   ├── 00000380.pro
│   │   │   │   │   ├── 00000381.pro
│   │   │   │   │   ├── 00000384.pro
│   │   │   │   │   └── 00000471.pro
│   │   │   │   └── items
│   │   │   │       └── 00000455.pro
│   │   │   ├── RAIDERS1.SAV
│   │   │   ├── REDDOWN.SAV
│   │   │   ├── REDDTUN.SAV
│   │   │   ├── REDMENT.SAV
│   │   │   ├── REDMTUN.SAV
│   │   │   ├── REDWAME.SAV
│   │   │   ├── REDWAN1.SAV
│   │   │   ├── RNDBRIDG.SAV
│   │   │   ├── SAVE.DAT
│   │   │   ├── SFCHINA2.SAV
│   │   │   ├── SFCHINA.SAV
│   │   │   ├── V15ENT.SAV
│   │   │   ├── V15SENT.SAV
│   │   │   ├── VAULT15.SAV
│   │   │   └── VCTYCTYD.SAV
│   │   ├── SLOT04
│   │   │   ├── ARBRIDGE.SAV
│   │   │   ├── ARCAVES.SAV
│   │   │   ├── ARTEMPLE.SAV
│   │   │   ├── ARVILLAG.SAV
│   │   │   ├── AUTOMAP.SAV
│   │   │   ├── NAVARRO.SAV
│   │   │   ├── proto
│   │   │   │   ├── critters
│   │   │   │   │   ├── 00000062.pro
│   │   │   │   │   ├── 00000079.pro
│   │   │   │   │   ├── 00000089.pro
│   │   │   │   │   ├── 00000097.pro
│   │   │   │   │   ├── 00000107.pro
│   │   │   │   │   ├── 00000136.pro
│   │   │   │   │   ├── 00000152.pro
│   │   │   │   │   ├── 00000160.pro
│   │   │   │   │   ├── 00000161.pro
│   │   │   │   │   ├── 00000162.pro
│   │   │   │   │   ├── 00000163.pro
│   │   │   │   │   ├── 00000164.pro
│   │   │   │   │   ├── 00000165.pro
│   │   │   │   │   ├── 00000191.pro
│   │   │   │   │   ├── 00000195.pro
│   │   │   │   │   ├── 00000196.pro
│   │   │   │   │   ├── 00000197.pro
│   │   │   │   │   ├── 00000265.pro
│   │   │   │   │   ├── 00000342.pro
│   │   │   │   │   ├── 00000379.pro
│   │   │   │   │   ├── 00000380.pro
│   │   │   │   │   ├── 00000381.pro
│   │   │   │   │   ├── 00000384.pro
│   │   │   │   │   └── 00000471.pro
│   │   │   │   └── items
│   │   │   │       └── 00000455.pro
│   │   │   ├── SAVE.DAT
│   │   │   └── SFCHINA.SAV
│   │   ├── SLOT05
│   │   │   └── proto
│   │   │       ├── critters
│   │   │       │   ├── 00000062.pro
│   │   │       │   ├── 00000079.pro
│   │   │       │   ├── 00000089.pro
│   │   │       │   ├── 00000097.pro
│   │   │       │   ├── 00000107.pro
│   │   │       │   ├── 00000136.pro
│   │   │       │   ├── 00000152.pro
│   │   │       │   ├── 00000160.pro
│   │   │       │   ├── 00000161.pro
│   │   │       │   ├── 00000162.pro
│   │   │       │   ├── 00000163.pro
│   │   │       │   ├── 00000164.pro
│   │   │       │   ├── 00000165.pro
│   │   │       │   ├── 00000191.pro
│   │   │       │   ├── 00000195.pro
│   │   │       │   ├── 00000196.pro
│   │   │       │   ├── 00000197.pro
│   │   │       │   ├── 00000265.pro
│   │   │       │   ├── 00000342.pro
│   │   │       │   ├── 00000379.pro
│   │   │       │   ├── 00000380.pro
│   │   │       │   ├── 00000381.pro
│   │   │       │   ├── 00000384.pro
│   │   │       │   └── 00000471.pro
│   │   │       └── items
│   │   │           └── 00000455.pro
│   │   ├── SLOT06
│   │   │   └── proto
│   │   │       ├── critters
│   │   │       │   ├── 00000062.pro
│   │   │       │   ├── 00000079.pro
│   │   │       │   ├── 00000089.pro
│   │   │       │   ├── 00000097.pro
│   │   │       │   ├── 00000107.pro
│   │   │       │   ├── 00000136.pro
│   │   │       │   ├── 00000152.pro
│   │   │       │   ├── 00000160.pro
│   │   │       │   ├── 00000161.pro
│   │   │       │   ├── 00000162.pro
│   │   │       │   ├── 00000163.pro
│   │   │       │   ├── 00000164.pro
│   │   │       │   ├── 00000165.pro
│   │   │       │   ├── 00000191.pro
│   │   │       │   ├── 00000195.pro
│   │   │       │   ├── 00000196.pro
│   │   │       │   ├── 00000197.pro
│   │   │       │   ├── 00000265.pro
│   │   │       │   ├── 00000342.pro
│   │   │       │   ├── 00000379.pro
│   │   │       │   ├── 00000380.pro
│   │   │       │   ├── 00000381.pro
│   │   │       │   ├── 00000384.pro
│   │   │       │   └── 00000471.pro
│   │   │       └── items
│   │   │           └── 00000455.pro
│   │   └── SLOT07
│   │       └── proto
│   │           ├── critters
│   │           │   ├── 00000062.pro
│   │           │   ├── 00000079.pro
│   │           │   ├── 00000089.pro
│   │           │   ├── 00000097.pro
│   │           │   ├── 00000107.pro
│   │           │   ├── 00000136.pro
│   │           │   ├── 00000152.pro
│   │           │   ├── 00000160.pro
│   │           │   ├── 00000161.pro
│   │           │   ├── 00000162.pro
│   │           │   ├── 00000163.pro
│   │           │   ├── 00000164.pro
│   │           │   ├── 00000165.pro
│   │           │   ├── 00000191.pro
│   │           │   ├── 00000195.pro
│   │           │   ├── 00000196.pro
│   │           │   ├── 00000197.pro
│   │           │   ├── 00000265.pro
│   │           │   ├── 00000342.pro
│   │           │   ├── 00000379.pro
│   │           │   ├── 00000380.pro
│   │           │   ├── 00000381.pro
│   │           │   ├── 00000384.pro
│   │           │   └── 00000471.pro
│   │           └── items
│   │               └── 00000455.pro
│   ├── SAVEGAME.tar.gz
│   ├── sound
│   │   └── music
│   │       ├── 01hub.acm
│   │       ├── 03wrldmp.acm
│   │       ├── 05raider.acm
│   │       ├── 07desert.acm
│   │       ├── 08vats.acm
│   │       ├── 10labone.acm
│   │       ├── 12junktn.acm
│   │       ├── 13carvrn.acm
│   │       ├── 14necro.acm
│   │       ├── 16follow.acm
│   │       ├── 17arroyo.acm
│   │       ├── 18modoc.acm
│   │       ├── 19reno.acm
│   │       ├── 20car.acm
│   │       ├── 21sf.acm
│   │       ├── 22vcity.acm
│   │       ├── 23world.acm
│   │       ├── 24redd.acm
│   │       ├── akiss.acm
│   │       ├── wind1.acm
│   │       └── wind2.acm
│   └── worldmap.dat
├── ddraw.dll
├── ddraw.ini
├── EULA.txt
├── Extras
│   ├── Hi-res text translations
│   │   └── Russian
│   │       └── ScrnSet.msg
│   └── ScrnSet.msg
├── f2.OLD
├── f2_res_change.log
├── f2_res_Config.exe
├── f2_res.dat
├── f2_res.dll
├── f2_res.ini
├── f2_res_patcher.exe
├── f2_res_README.rtf
├── fallout2-ce -> /home/rox/devel/fallout2-ce-1.3.0/b/fallout2-ce
├── fallout2-ce-debug
├── fallout2-ce.tar.gz
├── fallout2-ce.zip
├── fallout2.cfg
├── fallout2.cfg.bak
├── fallout2.exe
├── Fallout2_High_Resolution_Patch_4.1.8.exe
├── fallout2HR.exe
├── fallout2.ico
├── Fallout2Launcher.exe
├── FalloutClient.exe
├── FAQ.txt
├── GameuxInstallHelper.dll
├── goggame-1440151285.dll
├── goggame-1440151285.hashdb
├── goggame-1440151285.ico
├── goggame-1440151285.info
├── gog.ico
├── Launch Fallout 2.lnk
├── licence.txt
├── manual.pdf
├── master.dat
├── patch000.dat
├── Readme.rtf
├── refcard.pdf
├── runf2.sh
├── sfall-readme.txt
├── sound
│   └── music
│       ├── 01hub.acm
│       ├── 03wrldmp.acm
│       ├── 05raider.acm
│       ├── 07desert.acm
│       ├── 08vats.acm
│       ├── 10labone.acm
│       ├── 12junktn.acm
│       ├── 13carvrn.acm
│       ├── 14necro.acm
│       ├── 16follow.acm
│       ├── 17arroyo.acm
│       ├── 18modoc.acm
│       ├── 19reno.acm
│       ├── 20car.acm
│       ├── 21sf.acm
│       ├── 22vcity.acm
│       ├── 23world.acm
│       ├── 24redd.acm
│       ├── akiss.acm
│       ├── wind1.acm
│       └── wind2.acm
├── Support.ico
├── unins000.dat
├── unins000.exe
├── unins000.msg
└── webcache.zip

49 directories, 446 files

**Comment by psemiletov** [comment]
You can see the symlink to fallout executable where I build it and tried to debug loadsave.cc with messages to cout. By the way, the release 1.2 saves normal on my machine.

**Comment by alexbatalov** [comment]
It's definitely path resolver issue, but I was not able to reproduce it on macOS case-sensitive volume. Will try on Linux on the next week. Can you try on the most minimal setup:
```
critter.dat
master.dat
patch000.dat
sound/music/
```

Do not create anything else. Run the game and let it create remaining hierarchy (including `data`). Run new game, try save/load from the temple. If it works, copy just the `SAVEGAME` folder from your current installation.

**Comment by psemiletov** [comment]
Yes, now it works! Thank you!
