### ISSUE TITLE
Lost a boxing fight to  Xander Holyland without an actual fight

### ISSUE THREAD

**Issue by niamster** [alexbatalov/fallout2-ce#371]
A very strange bug: when fighting Xander Holyland (after losing to Masticator) in New Reno, the fight ends immediately (and Holyland wins with a knockout).
It seems like this is related https://gamefaqs.gamespot.com/boards/63576-fallout-2/56069129
The workaround from the guide above worked: start combat before entering the match.
I'm not sure whether it could be fixed in Fallout 2 CE though.

**Comment by phobos2077** [comment]
Probably a script issue. You can compare script with UPU version, see if there was any changes, maybe try that one. So you can rule out if this is an engine or content issue.

**Comment by FalloutClassicGamer** [comment]
> Probably a script issue. You can compare script with UPU version, see if there was any changes, maybe try that one. So you can rule out if this is an engine or content issue.

i use Killap patch everything is fine until i find bug when enter golden gate it crash instanly (android users)

**Comment by niamster** [comment]
> Probably a script issue. You can compare script with UPU version, see if there was any changes, maybe try that one. So you can rule out if this is an engine or content issue.

Can you please explain it again but if I'm like 5y old 😅 ?

**Comment by phobos2077** [comment]
> Can you please explain it again but if I'm like 5y old 😅 ?

Well you create an issue ticket on a game engine repository. If this is a script issue, then it's unrelated. If you can't look at the script, you can just fire a vanilla EXE and see if the bug is there with the same save.

**Comment by niamster** [comment]
> > Can you please explain it again but if I'm like 5y old 😅 ?
> 
> Well you create an issue ticket on a game engine repository. If this is a script issue, then it's unrelated. If you can't look at the script, you can just fire a vanilla EXE and see if the bug is there with the same save.

Thanks for the suggestion. I don't have a possibility to run vanilla exe so I can't verify whether this is related to engine or script issue.
