### ISSUE TITLE
Item Highlighting does not work with the GOG sourcefiles?

### ISSUE THREAD

**Issue by eglische** [alexbatalov/fallout2-ce#406]
Hello!
I decided to make a new post, as it seams my problem is somewhat related to another issue here, but not completely.

I'm under windows here, followed the installation instruction for fallout sonora 1.14 english translation:
https://www.moddb.com/mods/fallout-sonora-english/downloads/fallout-sonora-114-sonora-dayglow-114-english-translation-patch
fallout2-ce-windows-x86 is installed.

problem: when pressing shift the items nor the containers or bodies are highlighted.

shift key (dx key 42) also not working:
-installation is on under E:\Fallout 2\
-tried us layout -> not working
-made sure this setting is set in the ddraw.ini: ToggleItemHighlightsKey=42
-**it does highlight with fallout2.exe**, but it does not work when starting the game with fallout2-ce.exe

It is clear after those tests it has nothing to do with system input nor with the wrapper/hook.

on a side note, i tried to also run sonora 1.11 build from another source, that uses sfall 4.4.4 which also did not work. i asked in their github issues section for help, i was told that they don't support it because it's a modded version of sfall (i guess)

the game files comes from a us 1.02 GOG fo2 installation, neither the x.x.17 nor the x.x.18 release makes a difference.  (that's the GOG release version as can be downloaded there)

Thank you for any hints...

**Comment by phobos2077** [comment]
The answer is the same as in the other issue. Item highlight script relies on hook scripts which are not yet ported to CE:

```
      register_hook_proc(HOOK_KEYPRESS, KeyPressHandler);
      register_hook_proc(HOOK_COMBATTURN, CombatTurnHandler);
      register_hook_proc(HOOK_GAMEMODECHANGE, GameModeChangeHandler);
      register_hook_proc(HOOK_INVENTORYMOVE, InventoryMoveHandler);
```

This is not a vanilla feature, it's a fan-made mod that comes with sfall that adds this.
