### ISSUE TITLE
Headers cleanup

### ISSUE THREAD

**Issue by alexbatalov** [alexbatalov/fallout2-ce#42]
One of the rules I followed during decompilation - do not hide anything from yourself. That's why all functions, variables, and typedefs are exposed in headers. In order to prepare for code modernization phase headers need to be cleaned up of everything that might be considered implementation detail to appropriate module (i.e. private). That simply means moving many things from `h` files into `cc`, making variables and functions `static` in the process. In the end I expect whatever is left in headers is a part of public API. Please note that due to the way this project is structured, there might be some extreme cases like `editor.h` which has about 2-3 public functions and everything else is private. Don't forget to about moving includes. Prefer one `h`-`cc` pair per PR as it's easier to track.

---

- [x] `actions.h`
- [x] `animation.h`
- [x] `art.h`
- [x] `audio_file.h`
- [x] `audio.h`
- [x] `automap.h`
- [x] `autorun.h`
- [x] `cache.h`
- [x] `character_editor.h`
- [x] `character_selector.h`
- [x] `color.h`
- [x] `combat_ai_defs.h`
- [x] `combat_ai.h`
- [x] `combat_defs.h`
- [x] `combat.h`
- [x] `config.h`
- [ ] `core.h`
- [x] `credits.h`
- [x] `critter.h`
- [x] `cycle.h`
- [ ] `datafile.h`
- [x] `db.h`
- [x] `dbox.h`
- [x] `debug.h`
- [x] `dfile.h`
- [ ] `dialog.h`
- [x] `dictionary.h`
- [x] `dinput.h`
- [x] `display_monitor.h`
- [x] `draw.h`
- [x] `electronic_registration.h`
- [x] `elevator.h`
- [x] `endgame.h`
- [x] `export.h`
- [x] `file_find.h`
- [x] `file_utils.h`
- [x] `font_manager.h`
- [x] `game_config.h`
- [x] `game_dialog.h`
- [x] `game_memory.h`
- [x] `game_mouse.h`
- [x] `game_movie.h`
- [x] `game_palette.h`
- [x] `game_sound.h`
- [x] `game_vars.h`
- [x] `game.h`
- [x] `geometry.h`
- [x] `graph_lib.h`
- [x] `grayscale.h`
- [x] `heap.h`
- [x] `interface.h`
- [x] `interpreter_extra.h`
- [x] `interpreter_lib.h`
- [x] `interpreter.h`
- [x] `inventory.h`
- [x] `item.h`
- [x] `light.h`
- [x] `lips.h`
- [x] `loadsave.h`
- [x] `main.h`
- [x] `map_defs.h`
- [x] `map.h`
- [x] `memory_defs.h`
- [x] `memory_manager.h`
- [x] `memory.h`
- [x] `message.h`
- [x] `mmx.h`
- [ ] `mouse_manager.h`
- [x] `movie_effect.h`
- [x] `movie_lib.h`
- [x] `movie.h`
- [ ] `nevs.h`
- [x] `obj_types.h`
- [x] `object.h`
- [x] `options.h`
- [x] `palette.h`
- [x] `party_member.h`
- [x] `perk_defs.h`
- [x] `perk.h`
- [x] `pipboy.h`
- [x] `proto_instance.h`
- [x] `proto_types.h`
- [x] `proto.h`
- [x] `queue.h`
- [x] `random.h`
- [x] `reaction.h`
- [x] `region.h`
- [x] `scripts.h`
- [ ] `select_file_list.h`
- [ ] `selfrun.h`
- [x] `skill_defs.h`
- [x] `skill.h`
- [x] `skilldex.h`
- [x] `sound_decoder.h`
- [x] `sound_effects_cache.h`
- [x] `sound_effects_list.h`
- [x] `sound.h`
- [x] `stat_defs.h`
- [x] `stat.h`
- [x] `string_parsers.h`
- [x] `text_font.h`
- [x] `text_object.h`
- [x] `tile.h`
- [x] `trait_defs.h`
- [x] `trait.h`
- [ ] `trap.h`
- [x] `version.h`
- [x] `widget.h`
- [ ] `win32.h`
- [x] `window_manager_private.h`
- [x] `window_manager.h`
- [x] `window.h`
- [x] `word_wrap.h`
- [x] `world_map.h`
- [x] `xfile.h`

**Comment by k3tamina** [comment]
Should the PRs derived from these tasks be reconcilable with Reference Edition?

**Comment by alexbatalov** [comment]
I consider headers cleanup completed. Even though there are some headers left, most of them (probably except for `core.h`) contains some not yet decompiled functions, therefore it's unclear whether already decompiled functions are public or not.
