### ISSUE TITLE
Problem with compilation

### ISSUE THREAD

**Issue by Nikita-Sherstnev** [alexbatalov/fallout2-ce#43]
I have a problem with compilation. I use Manjaro 64 bit.

fallout2-ce/src/audio_file.cc:95:29: error: cast from ‘FILE*’ to ‘int’ loses precision [-fpermissive]
   95 |     audioFile->fileHandle = (int)stream;

**Comment by alexbatalov** [comment]
x64 is not yet supported, use x86 toolchain and libraries

**Comment by Nikita-Sherstnev** [comment]
I compiled it and ran. Very cool! But when I enter the temple map become black and textures are lagging.

**Comment by JanSimek** [comment]
It is a bug that happens if you are using a custom resolution from f2_res.ini instead of the default 640x480.

**Comment by Nikita-Sherstnev** [comment]
There is another problem: I can't save game and in the game folder appears files with Windows paths like "data\proto".

**Comment by alexbatalov** [comment]
I think I've fixed problem with tile borders (tried on 2560x1440). Please elaborate on textures lagging. Last time I checked linux  I had no problems on 1024x768 (1 vcpu, 2 gb ram).

**Comment by Risu** [comment]
Arroyo temple after new commit (2a9e00d7304363c704a1f8ff2cac65185ac80d35):
> Thread 1 "fallout2-ce" received signal SIGSEGV, Segmentation fault.
> fallout2-ce/src/object.cc:794
> 794                     int q = _light_get_tile(elevation, objectListNode->obj->tile);

**Comment by Nikita-Sherstnev** [comment]
> I think I've fixed problem with tile borders (tried on 2560x1440). Please elaborate on textures lagging. Last time I checked linux I had no problems on 1024x768 (1 vcpu, 2 gb ram).

I was able to move anywhere in screen, character and cursor behaved like this:
![image](https://user-images.githubusercontent.com/45091811/173234701-e2f941d7-81e5-49fc-934a-82ef8514ef6d.png)

Now game just crashes when I enter the temple with res 1920x1080.

**Comment by alexbatalov** [comment]
Please check if this one is fixed. There are rendering artefacts when map is out of bounds (corners on high resolutions), but they do not affect gameplay. We'll fix them later by rewriting tile rendering layer.

**Comment by Risu** [comment]
In README.md there is typo in "sudo apt install libsd2-2.0-0" -  should be libsdl.
When compiling under Ubuntu based distro there are errors in "tile.cc" regarding missing math.h include.
Sound is working in 64 bit executable. In 32 bit I got audio init error, probably some i386 sdl2 sound related library is missing in my distro.

**Comment by alexbatalov** [comment]
Typo fixed, thanks. Which Ubuntu version do you use? There are no missing includes complaints in CI (Ubuntu 20.04). In fact there was an include for `math.h`, but I think I removed it during headers cleanup. I've checked both architectures on virtualized Ubuntu, works for me. Since it fails on initialization I guess there is a problem in the SDL implementation and/or underlying driver. I will add error reporting from SDL to see what's going on.

**Comment by Risu** [comment]
20.04 FOCAL, "make" does not like atan2 in ttile.cc, including math.h is fixing this thing.
Regarding sound in 32bit I already checked and sdl error showing "dsp: No such audio devicesoundInit: Unable to init audio engine". I can control this with env variables like AUDIODEV and SDL_AUDIODRIVER, but switching to pulse or alsa only changing sdl error message. As result I think some i386 sdl2 audio library is missing on my system. But I am not concerned about this since 64 bit works fine.

**Comment by TerminalHash** [comment]
Don't playing music, video and in-game/menu sounds plays very well.
Artix Linux x86_64.

**Comment by alexbatalov** [comment]
I guess this is a path issue. First check `music_path1` in your `fallout2.cfg`, it's case-sensitive. Then in this directory (`DATA/SOUND/MUSIC`) try renaming `07DESERT.ACM` to `07desert.ACM` (music used in the main menu).

**Comment by JanSimek** [comment]
At least in the GOG version the filename `07desert.ACM` is correct. However, in case you don't know, this specific file is not packed inside `master.dat` like the other sound files but it's on its own in the `sound\music` directory so you have to copy the directory to `music_path1` location. I just found that out.

If that doesn't help, you can try enabling sound debug messages in the fallout2.cfg:

```ini
[sound]
debug=1
```

@alexbatalov on an unrelated subject, have you thought about using spdlog or simply creating a logging class that could handle different levels of messages severity info/warning/error/debug, origin and file output?

**Comment by alexbatalov** [comment]
Haven't thought of. I'm not sure we need fully featured logging solution. This is only a game, not a mission critical service where you probably want to log every single action, and logs are either the only way to understand what's going on or a way to monitor healthiness of the service. You have to be reasonable on who's the audience of this different levels of messages. For bug reports maximum verbosity will likely be needed to understand the problem. What's the use for minimum verbosity log?

**Comment by JanSimek** [comment]
Minimum verbosity log lets you quickly check for basic info like where files were loaded from or in this case a colourful warning message should be displayed about the missing 07desert.ACM instead of it being hidden under a sound debug configuration option. I think Falltergeist does it well.

**Comment by TerminalHash** [comment]
Steam version have 07desert.acm, not 07desert.ACM. After renaming music works.

**Comment by TerminalHash** [comment]
Also, this ugly resizing it's normal? %)
Videos:
![Снимок экрана от 2022-07-21 23-05-03](https://user-images.githubusercontent.com/64691722/180305682-8fa0910a-6ff9-4f15-9aa6-2350592efcba.png)

Menu:
![Снимок экрана от 2022-07-21 23-05-08](https://user-images.githubusercontent.com/64691722/180305698-1483a700-1498-4e24-bacf-c5570ee497c7.png)
