### ISSUE TITLE
Will this eventually support Fallout 1?

### ISSUE THREAD

**Issue by Kirtai** [alexbatalov/fallout2-ce#46]
As the title.

**Comment by Lexx2k** [comment]
https://github.com/alexbatalov/fallout2-re/issues/58#issuecomment-1126737402

**Comment by alexbatalov** [comment]
The way I envision it we'll have a separate launcher which will also act as updater where you'll be able to choose a setting to play, whether it's Fallout 1 (via Et Tu), Fallout 2, Nevada, etc. But that's not going to happen anytime soon, so don't hold your breath yet.

**Comment by Kirtai** [comment]
Ah, I didn't know about Et Tu. Nice project.

No rush, I just wanted to know if it was on the roadmap or not :)

Thanks.
