### ISSUE TITLE
HUD and Pre-rendered video little problems

### ISSUE THREAD

**Issue by APAmk2** [alexbatalov/fallout2-ce#73]
I downloaded 1.0.0 build now and tested it on Fallout:Nevada, first i seen is pre-rendered videos doesn't scaling to fullscreen and playing in native resolution 
![12_07_22_23-316](https://user-images.githubusercontent.com/107351397/178579834-5d273bfd-36aa-4f06-bca7-fa82d4ac6ab9.png)
And second i seen is a no borders for HUD
![scr00000](https://user-images.githubusercontent.com/107351397/178582796-7433df11-172a-41dc-99e0-1fab2a33ccfd.png)
BUT! That's playble, i want to try walkthrough game.

**Comment by Lexx2k** [comment]
Hi-Res patch is not fully ported over yet.

**Comment by APAmk2** [comment]
> Hi-Res patch is not fully ported over yet. What's working right now is only the bare minimum - higher resolution.
Yeah, i seen it just now, im a little bit stupid, thanks for informing me.
