### ISSUE TITLE
CE Changelog

### ISSUE THREAD

**Issue by alexeevdv** [alexbatalov/fallout2-ce#77]
Subj. Since we have releases now it would be great to have some kind of changelog. CHANGELOG.md in project root will do the trick i guess. 

F.e.: https://gitlab.com/OpenMW/openmw/-/blob/master/CHANGELOG.md

**Comment by alexbatalov** [comment]
I really don't know why they keep spending time managing this changelog. They have absolutely fantastic releases page https://gitlab.com/OpenMW/openmw/-/releases, which offers story-like introduction, table of contents, and clickable links to every fix and features in the release. Am I missing something?

**Comment by alexeevdv** [comment]
Releases are github/gitlab/whatever specific. You don't own it. Changelog is stored in the codebase
