### ISSUE TITLE
Game Crashes in PSVita in certain moments.

### ISSUE THREAD

**Issue by AnotherRandomPlayer** [alexbatalov/fallout2-ce#78]
When I try entering San Francisco or the scene of the innocent people being killed by the Enclave (tries to) play, the game crashes in the PSVita port
![Screenshot](https://user-images.githubusercontent.com/96704545/180195105-03fd421c-3279-497d-9ab6-ade605e9911b.PNG)
.

**Comment by alexbatalov** [comment]
I don't have Vita, so I'm not sure I can help you with this one. Attach your save game, I will check on desktops.

**Comment by AnotherRandomPlayer** [comment]
S
[SAVEGAME.zip](https://github.com/alexbatalov/fallout2-ce/files/9166630/SAVEGAME.zip)
ure!
