### ISSUE TITLE
french language

### ISSUE THREAD

**Issue by gwlegion** [alexbatalov/fallout2-ce#79]
crash when i set language to french ...

**Comment by Lexx2k** [comment]
language=french must be in fallout2.cfg, fo1_french must be enabled in ddraw.ini

**Comment by gwlegion** [comment]
sorry, i mean in the vita port

**Comment by gwlegion** [comment]
not your fault, i didn't say it, you can't guess ;)
i got text files in another folder Fallout 2\data\Text\French

**Comment by gwlegion** [comment]
i got it working ...deleted all files from multiples sources, and copying only gog french version ... looks like it's working

**Comment by gwlegion** [comment]
do you think it will be compatible with fallout 1 ?

**Comment by APAmk2** [comment]
That's is Fallout TWO decompilation project, not Fallout One, if you can, just use FalloutEtTu mod, that is a port of Fallout to Fallout 2 engine

**Comment by alexbatalov** [comment]
Language stuff besides English is not yet decompiled, so I can't say it will work on desktops. Especially when it comes to input accented characters.

**Comment by gwlegion** [comment]
> That's is Fallout TWO decompilation project, not Fallout One, if you can, just use FalloutEtTu mod, that is a port of Fallout to Fallout 2 engine

whoa ... i don't know this mod . what a great discover ! 
could it be possible to have this mod and F2 in the same "application" ? 
i mean, maybe copying mod files in a directory and have a menu inside F2 to load the mod instead of F2 ... so i could have in my psvita F1 and F2 playables !

**Comment by Lexx2k** [comment]
Et Tu doesn't work with CE yet, because it requires lots of Sfall features.

**Comment by gwlegion** [comment]
> Et Tu doesn't work with CE yet, because it requires lots of Sfall features that aren't implemented at this time.

maybe later ... i dream about playing F1 and F2 in good condition on my vita !

**Comment by Sergorov** [comment]
Salút gwlegion! 
I'm currently running into the same problem to get the German translation to work on the Vita port. Could you tell me in a bit more detail how you got the French version to work? It seems as soon as I copy over the master.dat of the German version it CE crashes. Same goes for the experimental android port by the way. When just executing the compiled .exe on PC there's no problem.

**Comment by gwlegion** [comment]
> Salút gwlegion! I'm currently running into the same problem to get the German translation to work on the Vita port. Could you tell me in a bit more detail how you got the French version to work? It seems as soon as I copy over the master.dat of the German version it CE crashes. Same goes for the experimental android port by the way. When just executing the compiled .exe on PC there's no problem.

hi ... 
i got the multi-languages files from gog. 
and i modify the config file to set it in french (language=french must be in fallout2.cfg)

**Comment by Sergorov** [comment]
Wow, that worked!!! Thank you so much!
Just copy your fallout2.cfg. along with the master.dat, critter.dat, update000.dat, data folder and sound folder. It seems to be imported along with the other files. This also works for the android version! I have played a couple of minutes and didn't encounter any issues so far, and everything is translated!
