### ISSUE TITLE
Fallout 2 Unofficial Patch support?

### ISSUE THREAD

**Issue by DvaMishkiLapa** [alexbatalov/fallout2-ce#80]
Are these modifications supported?
[Fallout 2 Unofficial Patch](https://github.com/BGforgeNet/Fallout2_Unofficial_Patch)
[Killap Unofficial Fallout 2 patch](http://www.killap.net/)

**Comment by Lexx2k** [comment]
They need Sfall, which is currently not supported by this project, so no.

**Comment by APAmk2** [comment]
"So no." But in future 90% chanse yes. That is not finished project and we all need to understand and remember that

**Comment by DvaMishkiLapa** [comment]
Got it. I dug a little deeper into your development process (which I should have done before the question :D). Glad you took on this difficult task.

The only thing I didn't find an answer to my question, are any of the original F2 problems fixed on your end? Or is it vanilla behavior, with all the flaws?

**Comment by alexbatalov** [comment]
Currently it's vanilla mostly. Only a couple of improvements from Sfall is integrated, notably HRP, but that was a while ago. I've spent most of this week researching Fallout 1. Will get back on integrating Sfall starting next week.
