### ISSUE TITLE
iOS performance issues

### ISSUE THREAD

**Issue by alexbatalov** [alexbatalov/fallout2-ce#81]
Palette fading is painfully slow on both iPhone and iPad. On iPhone viewport is scaled down, which makes virtually all text an unreadable mess. Gameplay performance is very poor. On iPad viewport is scaled up, which looks better, but since there is no antialiasing, there are unexpected pixels all over the screen. Performance-wise it's playable. It's definitely not ready for prime time due to rendering issues and lack of controls.

**Comment by FakelsHub** [comment]
Ну вобщето это тормозит не только на телефонах, а также на компьютерах. Не знаю зачем прикрутили этот всем известно тормозной SDL. Т.е. таже проблема с производительностью, что и с движком под названием falgertist, но там менее тормозит чем эта подделка.

**Comment by eduo** [comment]
> Palette fading is painfully slow on both iPhone and iPad. On iPhone viewport is scaled down, which makes virtually all text an unreadable mess. Gameplay performance is very poor. On iPad viewport is scaled up, which looks better, but since there is no antialiasing, there are unexpected pixels all over the screen. Performance-wise it's playable. It's definitely not ready for prime time due to rendering issues and lack of controls.

Wait. This runs on iOS? I didn't see an IPA in the releases so I assumed it just didn't.

(I understand you're sating it doesn't run well and it may be because it's not ready for consumption, but it's great news nonetheless. I'll keep my eyes peeled for a future update you feel comfortable with)
