### ISSUE TITLE
Noticed Bugs (PS Vita version)

### ISSUE THREAD

**Issue by CD4NV** [alexbatalov/fallout2-ce#82]
Hello everyone. I decided to make this branch, because I think it can be useful to the project as a beta testing.
I just started playing (reached Klamath) and have already discovered several bugs (I use PS Vita version 1.0.0-vita.2):
1) Cursor behavior during combat. During a fight, if the cursor was engaged before the opponent's turn, the cursor will move until the opponent finishes his turn.
2) The quest with Smoke (A Dog) does not work. When you reach the dog, it does not react to the player in any way. [SLOT08 (Smoke Bug).zip](https://github.com/alexbatalov/fallout2-ce/files/9172397/SLOT08.Smoke.Bug.zip)
3) At the first entrance to the city Klamath Sulik automatically becomes an ally. Sulik constantly runs from the building to the street. The first dialog occurs as usual, but when the dialog occurs for the second time, the dialog branches will be shown as if Sulik was already in the team. [SLOT01 (Sulik Bug).zip](https://github.com/alexbatalov/fallout2-ce/files/9172437/SLOT01.Sulik.Bug.zip)
4) When entering symbols (for example, when creating a character or when creating saves), the uppercase symbols does not work.

As the port progresses, I will supplement this post with new bugs discovered and thank you so much for this port, I've been waiting for it since I bought myself a PS Vita =)

**Comment by c6-dev** [comment]
If possible, provide a save file whenever you discover and report a bug so it can be easily reproduced by developers.

**Comment by CD4NV** [comment]
> If possible, provide a save file whenever you discover and report a bug so it can be easily reproduced by developers.
Ok, I will continue to follow this advice. Thanks.

**Comment by alexbatalov** [comment]
Sulik's problem is fixed. Smoke's probably too, as he starts following me as expected.

**Comment by Northfear** [comment]
@CD4NV I think the cursor problem might be related to the port itself

**Comment by CD4NV** [comment]
Installed a new version v1.0.0-vita.3 An error occurred when changing the screen resolution in the f2_res.ini file. I set the resolution to 600 x 340 and an error occurred: C2-12828-1
Dump file: [psp2core-1658597741-0x0000432d11-eboot.bin.zip](https://github.com/alexbatalov/fallout2-ce/files/9174298/psp2core-1658597741-0x0000432d11-eboot.bin.zip)

**Comment by CD4NV** [comment]
> @CD4NV I think the cursor problem might be related to the port itself

Perhaps, just in the original game (win version), such a problem was not noticed.

**Comment by alexbatalov** [comment]
You should not set resolution below 640x480. Many original art backgrounds are exactly 640x480 and are copied without boundary checks.

**Comment by Lexx2k** [comment]
Probably should add a safeguard to not allow resolutions smaller than the default.

**Comment by CD4NV** [comment]
5. Also noticed the following bug: When there is a dialogue with "talking heads", where voice acting is used, the game may crash when the audio file of the dialogue is interrupted by selecting a new branch of the dialogue (do not let the "talking head" utter a remark to the end).

**Comment by Northfear** [comment]
> 5. Also noticed the following bug: When there is a dialogue with "talking heads", where voice acting is used, the game may crash when the audio file of the dialogue is interrupted by selecting a new branch of the dialogue (do not let the "talking head" utter a remark to the end).

Same with interrupted video crashes. Could be some race condition in audio code.
@alexbatalov is there any kind of community discussion thing that's related to the project btw? (Discord, IRC, etc). I do have a few code related questions.

**Comment by alexbatalov** [comment]
I cannot reproduce your crashes on desktop platforms, but will review audio code.

@Northfear Use Discussions here on GitHub or open up a new issue.

**Comment by CD4NV** [comment]
6. The mechanics of opening doors with a shot from a firearm has been violated: [SLOT03 (Klamath Door).zip](https://github.com/alexbatalov/fallout2-ce/files/9176124/SLOT03.Klamath.Door.zip)
In the original game, any firearm could knock out the door.

**Comment by alexbatalov** [comment]
Please elaborate, I've checked with vanilla, behaviour looks the same.

Somehow you have broken your character's fid - you have weapon equipped (shown in the main slot), but it's not reflected on the screen (character appears unarmed). This can be fixed by swapping hands two times (you'll see rifle take out animation). I wonder how did you do that.

Please open up new issue every time you something strange. No need to keep everything in one thread.

**Comment by CD4NV** [comment]
>

**Comment by CD4NV** [comment]
> Somehow you have broken your character's fid - you have weapon equipped (shown in the main slot), but it's not reflected on the screen (character appears unarmed). This can be fixed by swapping hands two times (you'll see rifle take out animation). I wonder how did you do that.

I do not know, I just talked to the Danton brothers (without weapons). Later I tried to open the door, it turned out to be closed and I started hacking it with skills. After unsuccessful hacking attempts, I just went into the inventory and put the gun in one of the free slots and found that I could not shoot at the door.

> Please open up new issue every time you see something strange. No need to keep everything in one thread.

Ok, I will do so in the future.
