### ISSUE TITLE
Not recieving a flint after a sucessfull speech check in Arroyo

### ISSUE THREAD

**Issue by Northfear** [alexbatalov/fallout2-ce#83]
Flint is not in the inventory after a successful speech check.
Obtaining it by giving your aunt a healing powder works fine.
[SLOT10.zip](https://github.com/alexbatalov/fallout2-ce/files/9173311/SLOT10.zip)
PS. Just started a testing play through, so there's hopefully more bug reports on it's way.

**Comment by CD4NV** [comment]
I confirm the problem with the flint.
I also encountered this problem at the beginning, but for some reason I forgot to add it to my buglist.
