### ISSUE TITLE
Apple Silicon Support

### ISSUE THREAD

**Issue by tomkidd** [alexbatalov/fallout2-ce#84]
Howdy, I run the site [Mac Source Ports](https://macsourceports.com) and this looks like an excellent thing I could add to the site (I either make builds or point to builds of source ports for Mac, preferably with Apple Silicon support). 

So first off I can tell you yes the build you've got for Intel works fine on Apple Silicon via Rosetta 2.

And since it looks like the only real dependences this has are SDL2 and lib, I'm willing to bet it works on Apple Silicon without much effort.

I may take a swing at making a Universal 2 build but since you're signing and notarizing it if you want to do it yourself I'll just link to yours. 

Either way, this is outstanding work, thanks for sharing it with us.

**Comment by alexbatalov** [comment]
Great news, thanks for checking this. I will update build system to produce universal binary.

**Comment by alexbatalov** [comment]
@tomkidd v1.0.1 is available, you can update link to releases in this repo, as you mentioned the app bundle is signed and notarized as a part of release process. Thanks for spreading the word!
