### ISSUE TITLE
Fallout 2-CE on Debian

### ISSUE THREAD

**Issue by aknight2015** [alexbatalov/fallout2-ce#85]
When I try to run fallout2-ce I get a "couldn't find/load/text fonts." I've copied the entire data folder for fallout 2 over, and I put the fallout2-ce into the fallout 2 directory. It looks like this:
/Games/fallout2/
     -Data/
     -sound/
     -CRITTER.DAT
     -fallout2-ce
     -MASTER.DAT
     -PATCH000.DAT

**Comment by alexbatalov** [comment]
Lowercase your files - `critter.dat`, `master.dat`, `patch000.dat`, and `data`. Alternatively you can provide `fallout2.cfg` with paths matching your setup.

**Comment by aknight2015** [comment]
That did it. I can finally play one of my all time favorite games on my Chromebook.
