### ISSUE TITLE
Blank map when using higher resolution than 640x480

### ISSUE THREAD

**Issue by JanSimek** [alexbatalov/fallout2-ce#9]
It seems to happen only on larger maps such as arcaves.map and broken1.map and not the smaller ones such as artemple.map or desert1.map .

When loading certain maps the `tileSetCenter` function fails and returns -1 on the following check:

https://github.com/alexbatalov/fallout2-ce/blob/0c61f74ba990879135766892d7241ec7f300cf3d/src/tile.cc#L508-L512

My guess is that the code above checks whether the center tile is outside of the scroll block area. 

I suspect that the bug is somewhere in the `_tile_set_border` function. Specifically, this part looks suspicious as the `windowWidth` parameter is not used anywhere:

https://github.com/alexbatalov/fallout2-ce/blob/0c61f74ba990879135766892d7241ec7f300cf3d/src/tile.cc#L402-L405

**Comment by alexbatalov** [comment]
Check it on your map. I've seen something you describe in Gecko, but I'm not sure.

**Comment by JanSimek** [comment]
The problem is in the `tileFromScreenXY()` function which relies on the `_tile_offx` and `_tile_offy` variables. These are in turn calculated from ` gTileWindowWidth` (= real window width) and `gTileWindowHeight` (= real window height).

[HRP for reference](https://github.com/phobos2077/sfall/blob/41b4b773a3536365e83c3eba23f3073fac57c06e/sfall/HRP/ViewMap/ViewMap.cpp#L79)
