### ISSUE TITLE
Get book from Derek (False status)

### ISSUE THREAD

**Issue by CD4NV** [alexbatalov/fallout2-ce#90]
I haven't get this quest yet (you can check this by entering into a dialogue with Rebecca, asking her about new job), but it is already displayed in the status of the city as a recieved quest: [SLOT04 (The Den, Rebecca's Book).zip](https://github.com/alexbatalov/fallout2-ce/files/9177834/SLOT04.The.Den.Rebecca.s.Book.zip)
This happens immediately after the first completed quest from Rebecca ("Collect money from Fred").

**Comment by alexbatalov** [comment]
This is vanilla, no?

**Comment by CD4NV** [comment]
> This is vanilla, no?

What is vanilla? If you are asking about a specific version of the build, then I use the Steam version content.

**Comment by alexbatalov** [comment]
Vanilla is the original game without any modifications. Steam has some version of Sfall bundled, you might want to get rid of it to check behaviour in the original game. Copy original game data (`critter.dat`, `master.dat`, `patch000.dat` and `data` folder) and `fallout2.exe` to a new folder and run it. I've checked this quest with save game from #89. Get book from Derek appears immediately as I complete Collect money from Fred quest.

**Comment by CD4NV** [comment]
> Vanilla is the original game without any modifications. Steam has some version of Sfall bundled, you might want to get rid of it to check behaviour in the original game. Copy original game data (`critter.dat`, `master.dat`, `patch000.dat` and `data` folder) and `fallout2.exe` to a new folder and run it. I've checked this quest with save game from #89. Get book from Derek appears immediately as I complete Collect money from Fred quest.

I use PS Vita because in #82 you asked me to make a new issue for every bug found. All my posts relate only to the PS Vita version.
Ok, I'll try to replace the date files with the original ones, but something tells me that this is exactly the specifics of the PS Vita port.
