### ISSUE TITLE
No random encounters

### ISSUE THREAD

**Issue by Northfear** [alexbatalov/fallout2-ce#94]
Random encounters aren't triggering while traveling on the world map.
In the late AUG the first Frank Horrigan encounter starts up and the player receives a car after it's finished (but it's not shown on the town maps. Only on the world one)
[SLOT07.zip](https://github.com/alexbatalov/fallout2-ce/files/9193456/SLOT07.zip)
Game version 1.0.1
Tested on Linux x64 and Windows x64

**Comment by declanriordan1** [comment]
I’m still experiencing this bug, is there someway to fix it?

**Comment by alexbatalov** [comment]
Download latest build: https://github.com/alexbatalov/fallout2-ce/actions/runs/2749421486

**Comment by declanriordan1** [comment]
> Download latest build: https://github.com/alexbatalov/fallout2-ce/actions/runs/2749421486

Srry I'm a bit of a noob, but to use this build do I just copy the fallout2ce.exe to my fallout 2 folder from steam, and then copy to the vita?

**Comment by Northfear** [comment]
> > Download latest build: https://github.com/alexbatalov/fallout2-ce/actions/runs/2749421486
> 
> Srry I'm a bit of a noob, but to use this build do I just copy the fallout2ce.exe to my fallout 2 folder from steam, and then copy to the vita?

Oh.. latest Vita builds are here:
https://github.com/Northfear/fallout2-ce-vita/releases/tag/latest

**Comment by declanriordan1** [comment]
Interesting, I do have the latest build I guess I should ask around over there. It's so funny it is the exact opposite problem I usually have with fallout 2, usually the random encounters kick my ass and are kind of annoying. Might make leveling up a little harder though

**Comment by Northfear** [comment]
> Interesting, I do have the latest build I guess I should ask around over there. It's so funny it is the exact opposite problem I usually have with fallout 2, usually the random encounters kick my ass and are kind of annoying. Might make leveling up a little harder though

Just tested once more. Random encounters are happening for me. Maybe they're just not as frequent as you remember them to be

**Comment by declanriordan1** [comment]
> > Interesting, I do have the latest build I guess I should ask around over there. It's so funny it is the exact opposite problem I usually have with fallout 2, usually the random encounters kick my ass and are kind of annoying. Might make leveling up a little harder though
> 
> Just tested once more. Random encounters are happening for me. Maybe they're just not as frequent as you remember them to be

Hm very interesting. Tested myself and there are definitely no encounters on my end, I walked the length of the map and nothing. I’m at work but tonight I could upload my save file maybe you could try to reproduce it? Other than that I’ll probably just try to reinstall and see what happens
