### ISSUE TITLE
Enlarge the font in subtitles [PS Vita].

### ISSUE THREAD

**Issue by J013k** [alexbatalov/fallout2-ce#97]
Is there a chance to enlarge the font in subtitles?

Currently the default font is quite small:
![https://i.imgur.com/rnBxkp6.png](https://i.imgur.com/rnBxkp6.png)

![https://i.imgur.com/5mVkLxC.png](https://i.imgur.com/5mVkLxC.png)

![https://i.imgur.com/eX5tFof.png](https://i.imgur.com/eX5tFof.png)

**Comment by usb777** [comment]
Привет. Спасибо за Фолыч на Виту, это была моя мечта, хотел спонсировать комманду из Китая. Оставь счёт, Paypal или другое - перешлю денюшку за мечту.    Для связи  seodslab@gmail.com или номер +1347-283-8507

Man, you are cool. Left paypal or Else, I want send you money for PS VITA fallout.  You made my dream true
or ping me on seodslab@gmail.com

**Comment by J013k** [comment]
Are you a spammer?

I am asking because I am not the one that is responsible for this port or even this repo.

**Comment by APAmk2** [comment]
> Привет. Спасибо за Фолыч на Виту, это была моя мечта, хотел спонсировать комманду из Китая. Оставь счёт, Paypal или другое - перешлю денюшку за мечту.    Для связи  seodslab@gmail.com или номер +1347-283-8507
> 
> Man, you are cool. Left paypal or Else, I want send you money for PS VITA fallout.  You made my dream true
> or ping me on seodslab@gmail.com
> 

What the fuck... Man, i guess you don't know how github works, so you comment is inappropriate here. They can't receiving ANY donations, because Fallout 1 and 2 is property of Bethesda softworks, i think they are not very willing to waste time on the war with the army of lawyers microsoft, zenimax or Bethesda.

**Comment by alexbatalov** [comment]
I don't have Vita, so I'm not sure if that's font, scaling, or something else. It's perfectly fine on 6'' screen on Android, albeit yes, it's small. This is the default font which is used almost everywhere in the game, which is not going to be changed.

**Comment by usb777** [comment]
I'm not spammer. I want to tell thank you and donate for your work. Cos
Fallout2 on Mobile platform was my dream.
However I want to say THANK YOU. I'm real man. I left my email and phone
number.

**Comment by J013k** [comment]
@alexbatalov
PS Vita has 1 inch less... (5").
It will be nice if PS Vita port has an option (small, medium, large) to change size in subtitles.
If it cannot be done, then I am closing this issue.

@usb777
These people are responsible for PS Vita ports:
* https://github.com/Northfear/fallout2-ce-vita
* https://github.com/isage/fallout2-ce
