### ISSUE TITLE
Slim Picket in Klamath (learning bug)

### ISSUE THREAD

**Issue by CD4NV** [alexbatalov/fallout2-ce#98]
In the town of trappers there is such a character as Slim Pocket. For 100 (with a low reputation in Klamath) or 50 coins (with a high reputation), Slim Pocket can train a player to hunt Gekko. The bug lies in the fact that after training, the money is not received by Slim Pocket, but by the player.
This is a fairly well-known bug (in this case, it's not a port bug, it's a bug of the original game) and I thought it could fixed. If the goal of the project is to make the port match the original version of the game as much as possible, then I think that this bug can be left for authenticity and just close this issue.
Here's a save file: [SLOT01.zip](https://github.com/alexbatalov/fallout2-ce/files/9203426/SLOT01.zip)
I draw your attention to the fact that Slim Pocket is a rather capricious character and may not agree to teach the player the first time. You just need to ask him about it several times. Thanks.

**Comment by alexbatalov** [comment]
It's a scripting bug, not the engine itself. It's fixed in RP/UP. You'll have wait for Sfall integration before Community Edition can run these patches.

**Comment by CD4NV** [comment]
> It's a scripting bug, not the engine itself. It's fixed in RP/UP. You'll have wait for Sfall integration before Community Edition can run these patches.

Ok, thx.
