### ISSUE TITLE
Deliver a meal to Smitty for Mom

### ISSUE THREAD

**Issue by CD4NV** [alexbatalov/fallout2-ce#99]
After passing this quest, the interface just freezes. You cannot exit the dialog, you can only enter the inventory and barter.
[SLOT03.zip](https://github.com/alexbatalov/fallout2-ce/files/9219544/SLOT03.zip)

**Comment by alexbatalov** [comment]
This one was fixed in 39057fd1fbae70175b7b9d4a75587b027daf525b
